/* Pixel invariants for creative filters; no browser or third-party test runner. */
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),ctx={Uint8ClampedArray,Float32Array,Uint32Array,Int32Array,Math,self:{},console};vm.createContext(ctx);
vm.runInContext(['color.js','masks.js','filter-settings.js','filters.js','worker.js'].map(f=>fs.readFileSync(path.join(root,'src',f),'utf8')).join('\n'),ctx);
const defaults=()=>vm.runInContext('({...creativeDefaults(),vignette:0,grain:0,glow:0,blur:0,focusX:.5,focusY:.5,focusRadius:25})',ctx),results=[];
const test=(name,fn)=>{fn();results.push(name);console.log('PASS',name);};
function image(w,h,pixel){const d=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++)d.set(pixel(x,y),(y*w+x)*4);return d;}
const w=160,h=120,photo=image(w,h,(x,y)=>[x/w*230,y/h*255,(x+y)/(w+h)*180,255]);
function run(src,fx,W=w,H=h){let out=ctx.dehazePixels(new Uint8ClampedArray(src),W,H,fx);ctx.filmPixels(out,W,H,fx);ctx.halationPixels(out,W,H,fx);ctx.aberrationPixels(out,W,H,fx);ctx.grungePixels(out,W,H,fx);return out;}
test('All filters at zero are byte-identical; bypass retains neutral output',()=>{assert.deepEqual(run(photo,defaults()),photo);for(const key of ['halation','grunge','film','dehaze','aberration']){const fx=defaults();fx[key]=80;fx[key+'Enabled']=false;assert.deepEqual(run(photo,fx),photo);}});
test('Halation makes a warm halo around a highlight, without lifting remote shadows',()=>{const src=image(w,h,(x,y)=>x>70&&x<90&&y>50&&y<70?[255,255,255,255]:[15,15,15,255]),fx=defaults();fx.halation=90;fx.halationRadius=4;const out=run(src,fx),i=(60*w+68)*4;assert(out[i]>out[i+1]&&out[i+1]>=out[i+2]);assert(out[i]>src[i]);assert.equal(out[0],src[0]);assert.deepEqual(out.slice((60*w+80)*4,(60*w+80)*4+4),new Uint8ClampedArray([255,255,255,255]));});
test('Halation threshold and spread change the visible halo',()=>{const src=image(w,h,(x,y)=>x>65&&x<95&&y>45&&y<75?[200,200,200,255]:[15,15,15,255]),fx=defaults();fx.halation=100;fx.halationRadius=4;fx.halationThreshold=95;assert.deepEqual(run(src,fx),src);fx.halationThreshold=40;const wide=run(src,fx);fx.halationRadius=.5;assert.notDeepEqual(run(src,fx),wide);});
test('Grunge is repeatable, spatially varied, and seed-sensitive',()=>{const src=image(w,h,()=>[128,128,128,255]),fx=defaults();fx.grunge=70;const a=run(src,fx);assert.deepEqual(run(src,fx),a);assert(new Set(Array.from(a).filter((_,i)=>i%4===0)).size>30);fx.grungeSeed++;assert.notDeepEqual(run(src,fx),a);fx.grungeScale=90;assert.notDeepEqual(run(src,fx),a);});
test('Four film palettes differ; silver produces neutral monochrome',()=>{const fx=defaults();fx.film=100;fx.filmGrain=0;const sums=[];for(const profile of ['warm','cool','silver','faded']){fx.filmProfile=profile;const out=run(photo,fx);sums.push(Buffer.from(out).toString('base64'));if(profile==='silver')for(let i=0;i<out.length;i+=4){assert.equal(out[i],out[i+1]);assert.equal(out[i+1],out[i+2]);}}assert.equal(new Set(sums).size,4);});
test('Film fade and grain are controllable and grain is deterministic',()=>{const fx=defaults();fx.film=80;fx.filmGrain=0;const a=run(photo,fx);fx.filmFade=80;assert.notDeepEqual(run(photo,fx),a);fx.filmGrain=85;const b=run(photo,fx);assert.deepEqual(run(photo,fx),b);fx.filmGrainSize=90;assert.notDeepEqual(run(photo,fx),b);});
test('Dehaze recovers contrast in a synthetic hazy scene; negative adds haze',()=>{const src=image(w,h,(x,y)=>x>140?[235,240,245,255]:[100+(x%30)*2,110+(y%30)*2,120+(x%30),255]),fx=defaults();fx.dehaze=80;const out=run(src,fx),spread=d=>{const vals=[];for(let y=0;y<h;y++)for(let x=0;x<135;x++)vals.push(d[(y*w+x)*4]);return Math.max(...vals)-Math.min(...vals);};assert(spread(out)>spread(src));fx.dehaze=-70;const haze=run(src,fx);assert(spread(haze)<spread(src));assert(haze[0]>src[0]);});
test('Chromatic aberration preserves green and alpha and reverses red/blue fringes',()=>{const src=image(w,h,(x,y)=>[x>80?240:15,x>80?240:15,x>80?240:15,255]),fx=defaults();fx.aberration=100;fx.aberrationMode='linear';const a=run(src,fx);fx.aberration=-100;const b=run(src,fx);assert.notDeepEqual(a,src);for(let i=0;i<a.length;i+=4){assert.equal(a[i+1],src[i+1]);assert.equal(a[i+3],src[i+3]);assert.equal(a[i],b[i+2]);assert.equal(a[i+2],b[i]);}});
test('Radial aberration leaves its optical center fixed',()=>{const fx=defaults();fx.aberration=100;fx.aberrationCenterX=80/159*100;fx.aberrationCenterY=60/119*100;const a=run(photo,fx),i=(60*w+80)*4;assert.deepEqual(a.slice(i,i+4),photo.slice(i,i+4));assert.notDeepEqual(a,photo);});
test('Combined filters preserve every alpha value, including transparent edges',()=>{const src=image(w,h,(x,y)=>[x,255-y,255,x<8?0:x<20?128:255]),fx=defaults();for(const key of ['halation','grunge','film','dehaze','aberration'])fx[key]=80;const a=run(src,fx);for(let i=3;i<a.length;i+=4)assert.equal(a[i],src[i]);assert.deepEqual(a,run(src,fx));});
test('Tiny images and all-transparent images remain finite and stable',()=>{for(const [W,H]of [[1,1],[1,17],[17,1],[2,2]]){const src=image(W,H,()=>[100,120,140,0]),fx=defaults();for(const key of ['halation','grunge','film','dehaze','aberration'])fx[key]=100;assert.deepEqual(run(src,fx,W,H),src);}});
fs.mkdirSync(path.join(root,'.test-artifacts'),{recursive:true});fs.writeFileSync(path.join(root,'.test-artifacts','filters-results.json'),JSON.stringify({date:new Date().toISOString(),passed:results},null,2));
