/* Browser acceptance suite. Written for v1.4; see TEST-REPORT for execution status. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),art=path.join(root,'.test-artifacts');fs.mkdirSync(art,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const ready=async()=>{await page.waitForTimeout(150);await page.waitForFunction(()=>previewResult&&!renderRunning&&!exportBusy);};const test=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
await page.goto('file://'+path.join(root,'index.html'));await page.locator('#sample').click();await ready();
const fixture=await page.evaluate(()=>{const c=canvas(800,600),ctx=context(c);ctx.fillStyle='#7499ac';ctx.fillRect(0,0,800,600);ctx.fillStyle='#ef149a';ctx.fillRect(355,245,90,115);return c.toDataURL('image/png').split(',')[1];});await page.locator('#fileInput').setInputFiles({name:'eraser-object.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});await ready();
await test('Magic Eraser is visible in Easy mode and pointer painting creates a mask',async()=>{await page.locator('[data-tab="retouch"]').click();await ready();assert(await page.locator('#runMagic').isVisible());await page.locator('[data-number="eraser.radius"]').fill('10');await page.locator('[data-number="eraser.radius"]').blur();const rect=await page.locator('#overlay').boundingBox();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.43);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.58,{steps:15});await page.mouse.up();assert.equal(await page.evaluate(()=>state.eraser.mask.length),1);await page.screenshot({path:path.join(art,'v14-mask.png'),fullPage:true});});
await test('Removal shows a preview and Keep makes it undoable',async()=>{await page.locator('#runMagic').click();await page.waitForFunction(()=>magicPending&&!magicRunning,undefined,{timeout:120000});await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),0);await page.screenshot({path:path.join(art,'v14-preview.png'),fullPage:true});await page.locator('#keepMagic').click();await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),1);const pixel=await page.evaluate(()=>Array.from(context($('photo')).getImageData(Math.floor($('photo').width*.5),Math.floor($('photo').height*.5),1,1).data));assert(pixel[1]>80&&pixel[0]<220);await page.locator('#undo').click();await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),0);await page.locator('#redo').click();await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),1);});
await test('Reload and downloaded JSON retain the saved patch',async()=>{await page.waitForFunction(()=>$('saveState').dataset.state==='saved');await page.reload();await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),1);await page.locator('#projectMenu').click();const wait=page.waitForEvent('download');await page.locator('#saveProject').click();await (await wait).saveAs(path.join(art,'v14-browser-project.json'));const data=JSON.parse(fs.readFileSync(path.join(art,'v14-browser-project.json')));assert.equal(data.schema,4);assert(data.assets[data.settings.eraser.removals[0].asset]);await page.locator('#resetAll').click();await page.locator('#jsonInput').setInputFiles(path.join(art,'v14-browser-project.json'));await ready();assert.equal(await page.evaluate(()=>state.eraser.removals.length),1);});
await test('Refine, subtract mask, and cancellation preserve recoverable edits',async()=>{await page.locator('[data-tab="retouch"]').click();await page.locator('#refineLastMagic').click();assert.equal(await page.evaluate(()=>state.eraser.mask.length),1);await page.locator('#magicSubtract').click();const r=await page.locator('#overlay').boundingBox();await page.mouse.click(r.x+r.width*.1,r.y+r.height*.1);assert.equal(await page.evaluate(()=>state.eraser.mask.at(-1).mode),'subtract');await page.locator('#runMagic').click();await page.locator('#cancelMagic').click();await page.waitForFunction(()=>!magicRunning&&!exportBusy);assert.equal(await page.evaluate(()=>magicPending),null);assert(await page.evaluate(()=>state.eraser.mask.length>0));});
await test('Responsive panels and the existing clone brush remain reachable',async()=>{await page.locator('#cloneMode').click();assert(await page.locator('#pickClone').isVisible());await page.locator('#magicMode').click();await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(art,'v14-phone.png'),fullPage:true});for(const theme of ['light','contrast']){await page.selectOption('#theme',theme);await page.screenshot({path:path.join(art,'v14-phone-'+theme+'.png'),fullPage:true});}});
assert.deepEqual(errors,[]);results.push('No uncaught browser errors');fs.writeFileSync(path.join(art,'v14-browser-results.json'),JSON.stringify({date:new Date().toISOString(),passed:results},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
