'use strict';
const VERSION='1.4.0',SAMPLE='/*SAMPLE*/';
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x)),cap=(x,lo,hi)=>Math.min(hi,Math.max(lo,x));
const defaults=()=>({adjust:{exposure:0,brightness:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0,saturation:0,vibrance:0,warmth:0,tint:0,sharpen:0,structure:0},curves:Object.fromEntries(['rgb','r','g','b'].map(k=>[k,Array.from({length:9},(_,i)=>i*12.5)])),curveInterpolation:'linear',hsl:Object.fromEntries(colorBands.map(([k])=>[k,{hue:0,saturation:0,lightness:0}])),enabled:Object.fromEntries(editGroups.map(k=>[k,true])),geometry:{quarter:0,flipX:false,flipY:false,angle:0,perspectiveH:0,perspectiveV:0,fill:'transparent',fillColor:'#ffffff',expand:{left:0,right:0,top:0,bottom:0,fill:'transparent',color:'#ffffff'},crop:{x:0,y:0,w:1,h:1}},effects:{...creativeDefaults(),vignette:0,grain:0,glow:0,blur:0,focusX:.5,focusY:.5,focusRadius:25},eraser:eraserDefaults(),points:[],brushes:[],clones:[],text:{value:'',x:50,y:88,size:5,color:'#ffffff',font:'sans-serif',weight:'600',shadow:true},frame:{size:0,color:'#ffffff'},blend:{asset:'',opacity:35,mode:'screen'},look:'Original'});
const looks=[
 {name:'Original',values:{}},
 {name:'Clean light',values:{adjust:{exposure:.18,contrast:8,shadows:18,saturation:5,vibrance:16}}},
 {name:'Mountain air',values:{adjust:{contrast:18,shadows:14,highlights:-26,vibrance:30,structure:22,warmth:-8}}},
 {name:'Golden hour',values:{adjust:{exposure:.1,warmth:30,tint:4,shadows:15,contrast:7},effects:{glow:18,vignette:12}}},
 {name:'Silver print',values:{adjust:{saturation:-100,contrast:27,highlights:-10,shadows:10},effects:{grain:12,vignette:17}}},
 {name:'Noir',values:{adjust:{saturation:-100,contrast:43,blacks:-16,structure:20},effects:{grain:24,vignette:36}}},
 {name:'Faded film',values:{adjust:{saturation:-22,warmth:13,contrast:-10},curves:{rgb:[9,27,49,72,96]},effects:{grain:20,vignette:10}}},
 {name:'Cinema',values:{adjust:{contrast:19,saturation:-12,warmth:-9,tint:7},curves:{b:[7,29,50,72,95],r:[0,22,50,79,100]},effects:{vignette:22}}},
 {name:'Soft focus',values:{adjust:{contrast:-12,highlights:-18,warmth:7},effects:{glow:55}}},
 {name:'Copper',values:{adjust:{warmth:38,saturation:-40,contrast:14},curves:{b:[0,18,40,64,88]},effects:{grain:17}}},
 {name:'Electric',values:{adjust:{contrast:23,vibrance:65,saturation:22,structure:26},effects:{vignette:8}}},
 {name:'Cool paper',values:{adjust:{saturation:-83,warmth:-18,contrast:12},effects:{grain:15,glow:8}}}
];
let thumbnail=SAMPLE;
let state=defaults(),source=null,sourceImage=null,assets={},assetImages={},tab='looks',selectedPoint=0,curveChannel='rgb',localMode='point',brushKind='exposure',brushValue=.5,brushRadius=5,cloneRadius=3,cloneOpacity=85,cloneAnchor=null,clonePicking=false,cropDraft=null,cropRatio='free';
let history=[],historyIndex=-1,dirtyTimer=null,saveTimer=null,saveChain=Promise.resolve(),revision=0,renderSerial=0,renderRunning=false,renderAgain=false,renderTimer=null,previewResult=null,beforeResult=null,displayMatrix=null,displayScale=1,showBefore=false,exportBusy=false,drag=null,lastCommitted='',toastTimer=null,userLooks=[];
let db=null,dbFailed=false,worker=null,workerId=0,workerJobs=new Map();
const canvas=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
const context=c=>c.getContext('2d',{willReadFrequently:true});
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function fail(error){console.error(error);notify(error.message||String(error));}
function busy(on,text='Working…'){exportBusy=on;$('busy').hidden=!on;$('busyText').textContent=text;}
function setSave(kind,text){$('saveState').dataset.state=kind;$('saveState').textContent=text;}
function safePrefs(key,value){try{if(value===undefined)return localStorage.getItem('photobench-'+key);localStorage.setItem('photobench-'+key,value);}catch{}return null;}
function savePrefs(){safePrefs('theme',$('theme').value);safePrefs('mode',$('mode').value);}
function setMode(){document.body.dataset.mode=$('mode').value;if($('mode').value==='easy'&&['local'].includes(tab))setTab('looks');else renderPanel();savePrefs();}
function setTheme(){document.documentElement.dataset.theme=$('theme').value;savePrefs();drawHistogram();drawOverlay();}
function createWorker(){const url=URL.createObjectURL(new Blob([$('workerSource').textContent],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{const job=workerJobs.get(e.data.id);if(!job)return;workerJobs.delete(e.data.id);e.data.error?job.reject(new Error(e.data.error)):job.resolve(new Uint8ClampedArray(e.data.pixels));};worker.onerror=e=>{for(const j of workerJobs.values())j.reject(new Error('The image renderer stopped. Download a project backup and reload.'));workerJobs.clear();};}
function pixelsAsync(c,s){return new Promise((resolve,reject)=>{const w=c.width,h=c.height,d=context(c).getImageData(0,0,w,h);const id=++workerId;workerJobs.set(id,{resolve,reject});worker.postMessage({id,pixels:d.data.buffer,w,h,state:s},[d.data.buffer]);});}
function imageFromURL(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('This image could not be decoded. Use a JPEG, PNG, or WebP.'));im.src=url;});}
function fileURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('The file could not be read.'));r.readAsDataURL(file);});}
function openDB(){return new Promise(resolve=>{if(!window.indexedDB){dbFailed=true;resolve();return;}const request=indexedDB.open('photobench',1);request.onupgradeneeded=()=>request.result.createObjectStore('projects');request.onsuccess=()=>{db=request.result;db.onversionchange=()=>db.close();resolve();};request.onerror=()=>{dbFailed=true;resolve();};request.onblocked=()=>{dbFailed=true;resolve();};});}
function dbRead(){return new Promise((resolve,reject)=>{if(!db)return resolve(null);const r=db.transaction('projects').objectStore('projects').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function persist(){clearTimeout(saveTimer);if(!db){setSave('error','! Autosave unavailable — save JSON');return Promise.resolve();}const rev=revision,data=source?project():null;setSave('saving','◌ Saving locally');saveChain=saveChain.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite'),store=tx.objectStore('projects');data?store.put(data,'current'):store.delete('current');tx.oncomplete=()=>{if(rev===revision)setSave(source?'saved':'empty',source?'● Saved on this device':'○ No photo open');resolve();};tx.onerror=tx.onabort=()=>{setSave('error','! Autosave failed — save JSON');reject(new Error('Browser storage is full or unavailable. Download your project JSON to keep your work.'));};}));saveChain.catch(fail);return saveChain;}
function markDirty(){revision++;setSave('unsaved','○ Unsaved changes');clearTimeout(saveTimer);saveTimer=setTimeout(persist,600);}
function commit(label='Edit'){clearTimeout(dirtyTimer);const str=JSON.stringify(state);if(str!==lastCommitted){history=history.slice(0,historyIndex+1);history.push({label,state:copy(state)});if(history.length>50)history.shift();historyIndex=history.length-1;lastCommitted=str;markDirty();}syncButtons();}
function resetHistory(){history=[];historyIndex=-1;lastCommitted='';commit('Opened photo');}
function changed(label,commitNow=true,preserveLook=false){clearMagicPreview();if(!preserveLook)state.look=tab==='looks'?state.look:'Custom';if(commitNow)commit(label);else{setSave('unsaved','○ Unsaved changes');clearTimeout(dirtyTimer);dirtyTimer=setTimeout(()=>{commit(label);dirtyTimer=null;},350);}showBefore=false;$('compare').setAttribute('aria-pressed','false');requestRender();}
function undo(){if(magicPending){clearMagicPreview();renderPanel();requestRender();return;}if(dirtyTimer){commit('Edit');dirtyTimer=null;}if(historyIndex<=0)return;clearTimeout(dirtyTimer);historyIndex--;restoreHistory();}
function redo(){if(historyIndex>=history.length-1)return;clearTimeout(dirtyTimer);historyIndex++;restoreHistory();}
function restoreHistory(){clearMagicPreview();state=copy(history[historyIndex].state);lastCommitted=JSON.stringify(state);cropDraft=tab==='crop'?copy(state.geometry.crop):null;selectedPoint=Math.min(selectedPoint,state.points.length-1);markDirty();renderPanel();syncButtons();requestRender();notify(history[historyIndex].label);}
function syncButtons(){const has=!!source;for(const id of ['exportOpen','compare','resetTool','saveProject','resetAll','saveLook','stackOpen','snapshotOpen','recipeOpen'])$(id).disabled=!has;$('undo').disabled=!has||historyIndex<=0;$('redo').disabled=!has||historyIndex>=history.length-1;$('fileName').textContent=source?source.name:'Your next photograph';$('empty').hidden=has;$('photoWrap').hidden=!has;$('dimensions').textContent=source?`${source.width} × ${source.height} px${source.reduced?' · reduced working copy':''}`:'Open a photo to begin';}
async function decodeFile(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type)&&! /\.(jpe?g|png|webp)$/i.test(file.name))throw new Error('Choose a JPEG, PNG, or WebP image. RAW and HEIC are not supported in this release.');if(file.size>40*1024*1024)throw new Error('Choose an image smaller than 40 MB.');let url=await fileURL(file),im=await imageFromURL(url);const iw=im.naturalWidth,ih=im.naturalHeight,scale=Math.min(1,6000/iw,6000/ih,Math.sqrt(20000000/(iw*ih)));if(scale<1){const c=canvas(iw*scale,ih*scale);context(c).drawImage(im,0,0,c.width,c.height);url=c.toDataURL('image/png');im=await imageFromURL(url);}return{im,source:{name:file.name,dataURL:url,width:im.naturalWidth,height:im.naturalHeight,importWidth:iw,importHeight:ih,reduced:scale<1}};}
async function replacePhoto(file){if(source&&!confirm('Open another photo? Download a project first if you want to keep this session.'))return;busy(true,'Opening photo…');try{const item=await decodeFile(file);installPhoto(item.source,item.im,defaults(),{});if(item.source.reduced)notify(`Working copy reduced from ${item.source.importWidth} × ${item.source.importHeight} to ${item.source.width} × ${item.source.height} pixels.`);}catch(e){fail(e);}finally{busy(false);}}
function installPhoto(src,im,s,as,snaps=[]){clearMagicPreview();snapshotCache.clear();snapshots=snaps;compareSnapshot='';selectedBrush=-1;selectedClone=-1;brushAction='paint';clearTimeout(dirtyTimer);clearTimeout(saveTimer);renderSerial++;source=src;sourceImage=im;const tc=canvas(280,280*im.naturalHeight/im.naturalWidth);context(tc).drawImage(im,0,0,tc.width,tc.height);thumbnail=tc.toDataURL('image/jpeg',.75);state=s;assets=as;assetImages={};previewResult=null;beforeResult=null;cloneAnchor=null;selectedPoint=0;cropDraft=tab==='crop'?copy(state.geometry.crop):null;showBefore=false;$('compare').setAttribute('aria-pressed','false');resetHistory();syncButtons();renderPanel();requestRender();}
async function loadSample(){if(source&&!confirm('Replace this photo with the sample? Save a project first to keep it.'))return;busy(true,'Opening sample…');try{const im=await imageFromURL(SAMPLE);installPhoto({name:'Yosemite — Tunnel View.jpg',dataURL:SAMPLE,width:im.naturalWidth,height:im.naturalHeight,importWidth:im.naturalWidth,importHeight:im.naturalHeight,reduced:false},im,defaults(),{});}catch(e){fail(e);}finally{busy(false);}}
async function renderImage(s,maxEdge=1280,im=sourceImage,uncropped=false){s=effectiveSettings(s);maxEdge=safeRenderEdge(s,maxEdge);const scale=Math.min(1,maxEdge/Math.max(im.naturalWidth,im.naturalHeight)),base=canvas(im.naturalWidth*scale,im.naturalHeight*scale);context(base).drawImage(im,0,0,base.width,base.height);await drawRemovalLayers(base,s,base.width/im.naturalWidth,base.height/im.naturalHeight);drawClones(base,s);if(s.blend.asset&&assets[s.blend.asset]){let bi=assetImages[s.blend.asset];if(!bi)bi=assetImages[s.blend.asset]=await imageFromURL(assets[s.blend.asset]);const ctx=context(base),fit=Math.max(base.width/bi.naturalWidth,base.height/bi.naturalHeight),bw=bi.naturalWidth*fit,bh=bi.naturalHeight*fit;ctx.save();ctx.globalAlpha=s.blend.opacity/100;ctx.globalCompositeOperation=s.blend.mode;ctx.drawImage(bi,(base.width-bw)/2,(base.height-bh)/2,bw,bh);ctx.restore();}const pixels=await pixelsAsync(base,s);context(base).putImageData(new ImageData(pixels,base.width,base.height),0,0);const result=geometry(base,s,uncropped);if(!uncropped)finishCanvas(result.canvas,s);return result;}
function finishCanvas(c,s){const ctx=context(c),t=s.text;if(t.value){ctx.save();ctx.fillStyle=t.color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${t.weight} ${Math.max(6,c.width*t.size/100)}px ${t.font}`;if(t.shadow){ctx.shadowColor='#0009';ctx.shadowBlur=c.width*.005;ctx.shadowOffsetY=c.width*.001;}const lines=t.value.split('\n').slice(0,5),lineHeight=c.width*t.size/100*1.2;lines.forEach((line,i)=>ctx.fillText(line,c.width*t.x/100,c.height*t.y/100+(i-(lines.length-1)/2)*lineHeight,c.width*.95));ctx.restore();}if(s.frame.size){ctx.fillStyle=s.frame.color;const v=s.frame.size/100*Math.min(c.width,c.height);ctx.fillRect(0,0,c.width,v);ctx.fillRect(0,c.height-v,c.width,v);ctx.fillRect(0,0,v,c.height);ctx.fillRect(c.width-v,0,v,c.height);}}
function originalPreview(s,uncropped){s=effectiveSettings(s);const scale=Math.min(1,safeRenderEdge(s,previewLimit())/Math.max(source.width,source.height)),base=canvas(source.width*scale,source.height*scale);context(base).drawImage(sourceImage,0,0,base.width,base.height);return geometry(base,s,uncropped).canvas;}
function requestRender(){renderSerial++;clearTimeout(renderTimer);renderTimer=setTimeout(renderPreview,55);}
async function renderPreview(){if(!source)return;if(renderRunning){renderAgain=true;return;}renderRunning=true;renderAgain=false;const serial=renderSerial,s=magicPreviewSettings(copy(state)),im=sourceImage,uncropped=tab==='crop';$('renderState').textContent='Rendering preview…';try{const result=await renderImage(s,previewLimit(),im,uncropped);if(serial!==renderSerial)return;previewResult=result.canvas;displayMatrix=result.matrix;displayScale=result.sourceWidth/source.width;beforeResult=compareSnapshot?await snapshotPreview(compareSnapshot):originalPreview(s,uncropped);if(serial!==renderSerial)return;displayPhoto();drawHistogram();$('renderState').textContent=`${previewResult.width} × ${previewResult.height} preview`;}catch(e){fail(e);$('renderState').textContent='Preview failed';}finally{renderRunning=false;if(renderAgain||serial!==renderSerial)renderTimer=setTimeout(renderPreview,0);}}
function displayPhoto(){if(!previewResult)return;const c=$('photo'),im=showBefore?(beforeResult||previewResult):previewResult;c.width=im.width;c.height=im.height;context(c).drawImage(im,0,0);$('overlay').width=im.width;$('overlay').height=im.height;$('beforeBadge').hidden=!showBefore;$('beforeBadge').textContent=compareSnapshot?(snapshots.find(x=>x.id===compareSnapshot)?.name||'SNAPSHOT'):'ORIGINAL TONES';sizePhoto();drawOverlay();}
function sizePhoto(){if(!previewResult)return;const v=$('workspace'),margin=window.innerWidth<=760?24:48,fit=Math.min((v.clientWidth-margin)/$('photo').width,(v.clientHeight-margin)/$('photo').height,1),z=$('zoom').value==='fit'?fit:Number($('zoom').value);$('photoWrap').style.width=Math.max(1,$('photo').width*z)+'px';$('photoWrap').style.height=Math.max(1,$('photo').height*z)+'px';}
function drawHistogram(){const c=$('histogram'),ctx=context(c);ctx.clearRect(0,0,c.width,c.height);if(!previewResult)return;const bins=new Uint32Array(128),d=context(previewResult).getImageData(0,0,previewResult.width,previewResult.height).data;for(let i=0;i<d.length;i+=16)if(d[i+3])bins[Math.min(127,Math.floor((d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722)/2))]++;const max=Math.max(...bins,1);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');ctx.beginPath();ctx.moveTo(0,c.height);bins.forEach((n,i)=>ctx.lineTo(i/127*c.width,c.height-n/max*(c.height-5)));ctx.lineTo(c.width,c.height);ctx.fill();}
function drawBaseOverlay(){const c=$('overlay'),ctx=context(c);ctx.clearRect(0,0,c.width,c.height);if(showBefore||!source||!displayMatrix)return;const scale=c.width/(c.getBoundingClientRect().width||c.width);ctx.lineWidth=1.3*scale;ctx.strokeStyle='#d4fa7c';ctx.fillStyle='#d4fa7c';ctx.font=`${13*scale}px Arial`;
 if(tab==='crop'&&cropDraft){const r=cropDraft,x=r.x*c.width,y=r.y*c.height,w=r.w*c.width,h=r.h*c.height;ctx.fillStyle='#0008';ctx.beginPath();ctx.rect(0,0,c.width,c.height);ctx.rect(x,y,w,h);ctx.fill('evenodd');ctx.strokeStyle='#fff';ctx.strokeRect(x,y,w,h);ctx.strokeStyle='#ffffff77';for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(x+w*i/3,y);ctx.lineTo(x+w*i/3,y+h);ctx.moveTo(x,y+h*i/3);ctx.lineTo(x+w,y+h*i/3);ctx.stroke();}ctx.fillStyle='#fff';for(const [cx,cy]of[[x,y],[x+w,y],[x,y+h],[x+w,y+h]])ctx.fillRect(cx-3*scale,cy-3*scale,6*scale,6*scale);}
 if(tab==='local'&&localMode==='point')state.points.forEach((p,i)=>{const pt=displayMatrix.transformPoint({x:p.x*source.width*displayScale,y:p.y*source.height*displayScale}),r=p.radius/100*source.width*displayScale*Math.hypot(displayMatrix.a,displayMatrix.b);ctx.strokeStyle=i===selectedPoint?'#d4fa7c':'#fff';outlinePoint(ctx,p);ctx.stroke();ctx.fillStyle='#172114';ctx.beginPath();ctx.arc(pt.x,pt.y,12*scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),pt.x,pt.y);});
 if(tab==='retouch'&&retouchMode==='clone'&&cloneAnchor){const pt=displayMatrix.transformPoint({x:cloneAnchor[0]*source.width*displayScale,y:cloneAnchor[1]*source.height*displayScale});ctx.strokeStyle='#d4fa7c';ctx.beginPath();ctx.arc(pt.x,pt.y,8*scale,0,Math.PI*2);ctx.moveTo(pt.x-14*scale,pt.y);ctx.lineTo(pt.x+14*scale,pt.y);ctx.moveTo(pt.x,pt.y-14*scale);ctx.lineTo(pt.x,pt.y+14*scale);ctx.stroke();}
 if(drag&&drag.type==='stroke'){ctx.strokeStyle='#d4fa7caa';ctx.lineWidth=2*scale;ctx.beginPath();drag.stroke.path.forEach((p,i)=>{const pt=displayMatrix.transformPoint({x:p[0]*source.width*displayScale,y:p[1]*source.height*displayScale});i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y);});ctx.stroke();}
}
function escapeHTML(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function range(label,path,value,min=-100,max=100,step=1){const id='ctl-'+path.replace(/\./g,'-');return`<div class="range-field"><div class="row"><label for="${id}">${label}</label><input aria-label="${label} value" type="number" data-number="${path}" value="${value}" min="${min}" max="${max}" step="${step}"></div><input id="${id}" aria-label="${label}" data-range="${path}" type="range" value="${value}" min="${min}" max="${max}" step="${step}"></div>`;}
function adjustRange(k,l,min=-100,max=100,step=1){return range(l,'adjust.'+k,state.adjust[k],min,max,step);}
function effectsRange(k,l,min=0,max=100,step=1){return range(l,'effects.'+k,state.effects[k],min,max,step);}
function group(title,content,cls=''){return`<details class="group ${cls}" open><summary>${title}</summary>${content}</details>`;}
function setTab(name){if(name!=='retouch')clearMagicPreview();if(tab==='crop'&&name!=='crop')cropDraft=null;tab=name;safePrefs('tab',name);if(tab==='crop')cropDraft=copy(state.geometry.crop);showBefore=false;$('compare').setAttribute('aria-pressed','false');renderPanel();if(source)requestRender();}
function renderPanel(){const meta={looks:['01 / FIND YOUR FEEL','A starting point.'],adjust:['02 / SHAPE THE LIGHT','Tone & color.'],crop:['03 / FRAME THE MOMENT','Make the cut.'],local:['04 / WORK THE DETAILS','A lighter touch.'],retouch:['05 / REMOVE DISTRACTIONS','Clean things up.'],finish:['06 / MAKE IT YOURS','The finishing touch.']}[tab];$('panelEyebrow').textContent=meta[0];$('panelTitle').textContent=meta[1];document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));const body=$('panelBody');let html='';
 if(tab==='looks'){html='<p class="hint">Start with a look. Every adjustment stays editable.</p><div class="looks-grid">'+[...looks,...userLooks].map((l,i)=>`<button class="look${state.look===l.name?' active':''}" data-look="${i}" ${!source?'disabled':''}><img alt="" src="${source?thumbnail:SAMPLE}" style="filter:${lookCSS(l.name)}"><span>${escapeHTML(l.name)}</span></button>`).join('')+'</div><p class="hint small" style="margin-top:16px">Thumbnails suggest the look. The main preview renders the actual edit.</p>';if(userLooks.length)html+='<button id="clearLooks" class="text-button">Clear saved looks</button>';}
 if(tab==='adjust'){html=adjustRange('exposure','Exposure (EV)',-3,3,.05)+adjustRange('brightness','Brightness')+adjustRange('contrast','Contrast')+adjustRange('highlights','Highlights')+adjustRange('shadows','Shadows')+group('Color',adjustRange('saturation','Saturation')+adjustRange('vibrance','Vibrance')+adjustRange('warmth','Warmth')+`<div class="advanced">${adjustRange('tint','Tint')}</div>`)+group('Details',adjustRange('whites','Whites')+adjustRange('blacks','Blacks')+adjustRange('structure','Structure',0,100)+adjustRange('sharpen','Sharpen',0,100),'advanced')+group('Curves',`<label class="field">Channel<select id="curveChannel">${['rgb','r','g','b'].map(k=>`<option value="${k}" ${k===curveChannel?'selected':''}>${{rgb:'Master RGB',r:'Red',g:'Green',b:'Blue'}[k]}</option>`).join('')}</select></label><svg class="curve-svg" viewBox="0 0 200 100" aria-label="Tone curve"><path d="M0 75H200M0 50H200M0 25H200M50 0V100M100 0V100M150 0V100" stroke="var(--line)" stroke-width=".5"/><path d="M0 100L200 0" stroke="var(--muted)" stroke-dasharray="3 3"/><polyline id="curveLine" fill="none" stroke="var(--accent)" stroke-width="2" points="${state.curves[curveChannel].map((v,i)=>`${i*50},${100-v}`).join(' ')}"/></svg>`+['Black','Shadow','Midtone','Highlight','White'].map((n,i)=>range(n+' output',`curves.${curveChannel}.${i}`,state.curves[curveChannel][i],0,100)).join('')+'<button id="linearCurve" class="full">Reset this curve</button>','advanced');}
 if(tab==='crop'){const r=cropDraft||state.geometry.crop;html='<p class="hint">Drag a new rectangle on the photo, or set exact bounds below. Crop is always reversible.</p><label class="field">Aspect ratio<select id="cropRatio">'+[['free','Free'],['original','Original'],['1','1:1 · Square'],['1.333333333','4:3 · Landscape'],['1.5','3:2 · Landscape'],['1.777777778','16:9 · Widescreen'],['0.8','4:5 · Portrait'],['0.666666667','2:3 · Portrait'],['0.5625','9:16 · Story']].map(([v,l])=>`<option value="${v}" ${cropRatio===v?'selected':''}>${l}</option>`).join('')+'</select></label><div class="two-cols">'+[['x','Left'],['y','Top'],['w','Width'],['h','Height']].map(([k,l])=>`<label class="field">${l} %<input id="crop-${k}" data-crop="${k}" type="number" min="${k==='w'||k==='h'?1:0}" max="100" step=".1" value="${+(r[k]*100).toFixed(2)}"></label>`).join('')+'</div><div class="button-row"><button id="applyCrop" class="accent">Apply crop</button><button id="fullCrop">Full image</button></div>'+group('Orientation','<div class="button-row"><button id="rotateLeft" title="Rotate left 90 degrees">↶ 90°</button><button id="rotateRight" title="Rotate right 90 degrees">↷ 90°</button></div><div class="button-row"><button id="flipX">Flip horizontal</button><button id="flipY">Flip vertical</button></div>'+range('Straighten (°)','geometry.angle',state.geometry.angle,-30,30,.1)+'<p class="hint">Straightening zooms slightly to keep the edges filled. Rotation and flip reset the crop bounds.</p>');}
 if(tab==='local'){html='<div class="button-row"><button id="pointMode" aria-pressed="'+(localMode==='point')+'">Control points</button><button id="brushMode" aria-pressed="'+(localMode==='brush')+'">Brush</button></div>';if(localMode==='point'){html+='<p class="hint">Add a point, then drag it onto the area to change. Points stay attached to the original photo.</p><button id="addPoint" class="accent full">Add control point</button><div class="point-list">'+state.points.map((p,i)=>`<button data-point="${i}" aria-pressed="${i===selectedPoint}">Point ${i+1}</button>`).join('')+'</div>';const p=state.points[selectedPoint];if(p)html+=range('Horizontal position %','point.x',p.x*100,0,100)+range('Vertical position %','point.y',p.y*100,0,100)+range('Radius % of source width','point.radius',p.radius,1,75)+range('Feather','point.feather',p.feather,5,100)+range('Exposure (EV)','point.exposure',p.exposure,-3,3,.05)+range('Saturation','point.saturation',p.saturation)+range('Warmth','point.warmth',p.warmth)+'<button id="deletePoint" class="full">Remove selected point</button>';html+='<p class="note">Soft radial masks, up to 12 points. These are spatial adjustments, without automatic subject or color detection.</p>';}else{html='<div class="button-row"><button id="pointMode">Control points</button><button id="brushMode" aria-pressed="true">Brush</button></div><p class="hint">Paint on the photograph. Each stroke applies one soft adjustment.</p><label class="field">Adjustment<select id="brushKind">'+['exposure','saturation','warmth'].map(k=>`<option ${k===brushKind?'selected':''} value="${k}">${k[0].toUpperCase()+k.slice(1)}</option>`).join('')+'</select></label>'+range('Brush radius %','ui.brushRadius',brushRadius,.5,20,.5)+range(brushKind==='exposure'?'Exposure (EV)':'Strength','ui.brushValue',brushValue,brushKind==='exposure'?-2:-100,brushKind==='exposure'?2:100,brushKind==='exposure'?.1:1)+`<p class="pill">${state.brushes.length} / 60 strokes</p><button id="clearBrush" class="full">Erase all adjustment strokes</button><p class="note">Use Undo to remove the last stroke. For keyboard editing, use control points with numeric positions.</p>`;}}
 if(tab==='retouch'&&retouchMode==='clone'){html='<p class="hint">Clone a clean area over a small distraction. Pick a source, then paint where you want to use it.</p><button id="pickClone" class="accent full">'+(clonePicking?'Click a source on the photo…':'Pick clone source')+'</button><div class="two-cols"><label class="field">Source X %<input type="number" id="cloneX" min="0" max="100" step=".1" value="'+(cloneAnchor?(cloneAnchor[0]*100).toFixed(1):50)+'"></label><label class="field">Source Y %<input type="number" id="cloneY" min="0" max="100" step=".1" value="'+(cloneAnchor?(cloneAnchor[1]*100).toFixed(1):50)+'"></label></div><button id="numericClone" class="full">Set source from coordinates</button>'+range('Clone radius %','ui.cloneRadius',cloneRadius,.5,15,.5)+range('Opacity','ui.cloneOpacity',cloneOpacity,5,100)+`<p class="pill">${state.clones.length} / 60 clone strokes</p><button id="clearClones" class="full">Remove all clone strokes</button><p class="note">Samples the photo after kept Magic Eraser repairs, using a soft edge. Best for small blemishes on similar textures.</p>`;}
 if(tab==='retouch'){html=retouchChooser()+(retouchMode==='magic'?magicPanel():html);}
 if(tab==='finish'){html=creativePanel()+effectsRange('vignette','Vignette',-70,100)+effectsRange('grain','Grain')+effectsRange('glow','Glow')+group('Lens blur',effectsRange('blur','Blur strength')+effectsRange('focusRadius','Focus radius %',2,80)+effectsRange('focusX','Focus horizontal',0,1,.01)+effectsRange('focusY','Focus vertical',0,1,.01))+group('Text',`<label class="field">Caption<textarea id="caption" rows="2" maxlength="300" placeholder="Your words, if you want them">${escapeHTML(state.text.value)}</textarea></label><div class="two-cols"><label class="field">Color<input type="color" id="textColor" value="${state.text.color}"></label><label class="field">Typeface<select id="textFont">${[['sans-serif','Sans serif'],['serif','Serif'],['monospace','Monospace']].map(([v,l])=>`<option value="${v}" ${state.text.font===v?'selected':''}>${l}</option>`).join('')}</select></label></div>`+range('Text size %','text.size',state.text.size,1,20,.5)+range('Text horizontal %','text.x',state.text.x,0,100)+range('Text vertical %','text.y',state.text.y,0,100)+`<label class="inline-toggle"><input id="textShadow" type="checkbox" ${state.text.shadow?'checked':''}>Soft text shadow</label>`)+group('Frame',range('Inset border %','frame.size',state.frame.size,0,15,.5)+`<label class="field">Border color<input type="color" id="frameColor" value="${state.frame.color}"></label>`)+group('Double exposure',`<p class="hint">Blend another photo, centered to fill the source image.</p><button id="addBlend" class="full">${state.blend.asset?'Replace':'Open'} second photo</button>`+range('Blend opacity','blend.opacity',state.blend.opacity,0,100)+`<label class="field">Blend mode<select id="blendMode">${['screen','multiply','overlay','soft-light','source-over'].map(k=>`<option value="${k}" ${state.blend.mode===k?'selected':''}>${k==='source-over'?'Normal':k}</option>`).join('')}</select></label><button id="removeBlend" class="full" ${!state.blend.asset?'disabled':''}>Remove second photo</button>`,'advanced');}
 body.innerHTML=`<fieldset ${!source&&tab!=='looks'?'disabled':''} style="border:0;margin:0;padding:0;min-width:0">${html}</fieldset>`;extendPanelV12();extendWorkspacePanel();wirePanel();wireWorkspacePanel();wirePanelV12();wireCreativePanel();wireMagicPanel();drawOverlay();}
function lookCSS(n){return({'Original':'none','Clean light':'brightness(1.1) saturate(1.1)','Mountain air':'contrast(1.2) saturate(1.2)','Golden hour':'sepia(.3) saturate(1.3)','Silver print':'grayscale(1) contrast(1.2)','Noir':'grayscale(1) contrast(1.6)','Faded film':'sepia(.3) contrast(.85)','Cinema':'contrast(1.2) hue-rotate(10deg)','Soft focus':'contrast(.9) brightness(1.1)','Copper':'sepia(.6)','Electric':'saturate(1.7) contrast(1.2)','Cool paper':'grayscale(.85) sepia(.15)'})[n]||'none';}
function setPath(path,value){if(path==='effects.grungeSeed')value=Math.round(value);if(rangeEdit(path,value))return true;const parts=path.split('.');if(parts[0]==='ui'){({brushRadius:v=>brushRadius=v,brushValue:v=>brushValue=v,cloneRadius:v=>cloneRadius=v,cloneOpacity:v=>cloneOpacity=v})[parts[1]](value);return false;}if(parts[0]==='point'){const p=state.points[selectedPoint];if(p)p[parts[1]]=['x','y'].includes(parts[1])?value/100:value;}else{let obj=state;for(const k of parts.slice(0,-1))obj=obj[k];obj[parts.at(-1)]=value;}if(parts[0]==='curves')updateCurveGraph();return true;}
function wirePanel(){const bind=(id,event,fn)=>{if($(id))$(id).addEventListener(event,fn);};
 document.querySelectorAll('[data-range],[data-number]').forEach(el=>{el.addEventListener('input',()=>{if(el.value===''||!Number.isFinite(Number(el.value)))return;const path=el.dataset.range||el.dataset.number,v=cap(Number(el.value),Number(el.min),Number(el.max));document.querySelectorAll(`[data-range="${path}"],[data-number="${path}"]`).forEach(other=>{if(other!==el)other.value=v;});if(setPath(path,v))changed(path,false);});el.addEventListener('change',()=>{const path=el.dataset.range||el.dataset.number,v=cap(Number(el.value)||0,Number(el.min),Number(el.max));el.value=v;document.querySelectorAll(`[data-range="${path}"],[data-number="${path}"]`).forEach(other=>other.value=v);if(setPath(path,v))changed('Adjusted '+path);});});
 document.querySelectorAll('[data-look]').forEach(el=>el.onclick=()=>{const l=[...looks,...userLooks][+el.dataset.look],d=defaults();for(const k of ['adjust','curves','effects'])state[k]={...d[k],...copy(l.values[k]||{})};for(const k of ['rgb','r','g','b'])state.curves[k]=curveNine(state.curves[k]);state.hsl=copy(l.values.hsl||d.hsl);state.curveInterpolation=l.values.curveInterpolation||'linear';for(const k of ['adjust','curves','effects','hsl'])state.enabled[k]=true;state.look=l.name;changed('Look: '+l.name);renderPanel();});
 bind('clearLooks','click',()=>{if(confirm('Delete all saved looks? This does not change the current photo.')){userLooks=[];safePrefs('looks','[]');renderPanel();}});
 bind('curveChannel','change',e=>{curveChannel=e.target.value;renderPanel();});bind('linearCurve','click',()=>{state.curves[curveChannel]=Array.from({length:9},(_,i)=>i*12.5);changed('Reset curve');renderPanel();});
 bind('cropRatio','change',e=>{cropRatio=e.target.value;fitCropRatio();renderPanel();});
 document.querySelectorAll('[data-crop]').forEach(el=>el.onchange=()=>{const k=el.dataset.crop;cropDraft[k]=cap(Number(el.value)/100,k==='w'||k==='h'?.01:0,1);cropDraft.w=Math.min(cropDraft.w,1-cropDraft.x);cropDraft.h=Math.min(cropDraft.h,1-cropDraft.y);if(cropDraft.w<.01){cropDraft.x=.99;cropDraft.w=.01;}if(cropDraft.h<.01){cropDraft.y=.99;cropDraft.h=.01;}cropRatio='free';renderPanel();});
 bind('applyCrop','click',()=>{state.geometry.crop=copy(cropDraft);changed('Crop applied');setTab('adjust');});bind('fullCrop','click',()=>{cropDraft={x:0,y:0,w:1,h:1};state.geometry.crop=copy(cropDraft);cropRatio='free';changed('Full image');renderPanel();});
 function orient(fn){fn();state.geometry.crop={x:0,y:0,w:1,h:1};cropDraft=copy(state.geometry.crop);changed('Orientation');renderPanel();}
 bind('rotateLeft','click',()=>orient(()=>state.geometry.quarter=(state.geometry.quarter+3)%4));bind('rotateRight','click',()=>orient(()=>state.geometry.quarter=(state.geometry.quarter+1)%4));bind('flipX','click',()=>orient(()=>state.geometry.flipX=!state.geometry.flipX));bind('flipY','click',()=>orient(()=>state.geometry.flipY=!state.geometry.flipY));
 bind('pointMode','click',()=>{localMode='point';renderPanel();});bind('brushMode','click',()=>{localMode='brush';renderPanel();});bind('addPoint','click',()=>{if(state.points.length>=12)return notify('A photo can have up to 12 control points.');const center=sourcePoint(.5,.5);state.points.push({x:center[0],y:center[1],radius:18,feather:60,exposure:.35,saturation:0,warmth:0});selectedPoint=state.points.length-1;changed('Added control point');renderPanel();});document.querySelectorAll('[data-point]').forEach(el=>el.onclick=()=>{selectedPoint=+el.dataset.point;renderPanel();});bind('deletePoint','click',()=>{state.points.splice(selectedPoint,1);selectedPoint=Math.max(0,selectedPoint-1);changed('Removed control point');renderPanel();});bind('brushKind','change',e=>{brushKind=e.target.value;brushValue=brushKind==='exposure'?.5:20;renderPanel();});bind('clearBrush','click',()=>{state.brushes=[];changed('Cleared brush strokes');renderPanel();});
 bind('pickClone','click',()=>{clonePicking=true;renderPanel();});bind('numericClone','click',()=>{cloneAnchor=[cap(Number($('cloneX').value)||0,0,100)/100,cap(Number($('cloneY').value)||0,0,100)/100];clonePicking=false;notify('Clone source selected. Paint on the photo.');drawOverlay();});bind('clearClones','click',()=>{state.clones=[];changed('Cleared clone strokes');renderPanel();});
 bind('caption','input',e=>{state.text.value=e.target.value;changed('Caption',false);});bind('textColor','input',e=>{state.text.color=e.target.value;changed('Text color',false);});bind('frameColor','input',e=>{state.frame.color=e.target.value;changed('Frame color',false);});bind('textFont','change',e=>{state.text.font=e.target.value;changed('Typeface');});bind('textShadow','change',e=>{state.text.shadow=e.target.checked;changed('Text shadow');});bind('addBlend','click',()=>$('blendInput').click());bind('removeBlend','click',()=>{state.blend.asset='';changed('Removed double exposure');renderPanel();});bind('blendMode','change',e=>{state.blend.mode=e.target.value;changed('Blend mode');});
}
function fitCropRatio(){if(cropRatio==='free')return;const ratio=cropRatio==='original'?(state.geometry.quarter%2?source.height/source.width:source.width/source.height):Number(cropRatio),imageRatio=state.geometry.quarter%2?source.height/source.width:source.width/source.height;let w=1,h=1;if(imageRatio>ratio)w=ratio/imageRatio;else h=imageRatio/ratio;cropDraft={x:(1-w)/2,y:(1-h)/2,w,h};drawOverlay();}
function sourcePoint(nx,ny){if(!displayMatrix||!previewResult||!source)return[.5,.5];const p=displayMatrix.inverse().transformPoint({x:nx*previewResult.width,y:ny*previewResult.height});return[cap(p.x/(source.width*displayScale),0,1),cap(p.y/(source.height*displayScale),0,1)];}
function eventPoint(e){const r=$('overlay').getBoundingClientRect();return[cap((e.clientX-r.left)/r.width,0,1),cap((e.clientY-r.top)/r.height,0,1)];}
function beginPointer(e){if(handleWorkspacePointerStart(e))return;if(!source||showBefore||exportBusy||(renderRunning&&!(tab==='retouch'&&retouchMode==='magic')))return;const [nx,ny]=eventPoint(e),p=sourcePoint(nx,ny);$('overlay').setPointerCapture(e.pointerId);if(tab==='crop'){cropPointerStart(nx,ny);}else if(tab==='local'&&localMode==='point'){let idx=-1,best=Infinity;state.points.forEach((q,i)=>{const d=Math.hypot(q.x-p[0],(q.y-p[1])*source.height/source.width);if(d<best){best=d;idx=i;}});if(idx>=0&&best<.09){selectedPoint=idx;drag={type:'point',index:idx};renderPanel();}}else if(tab==='local'&&localMode==='brush'){if(brushAction==='erase'){if(selectedBrush<0)return notify('Choose a stroke to erase.');if((state.brushes[selectedBrush].erasers||[]).length>=30)return notify('30 eraser paths reached for this stroke.');drag={type:'erase',index:selectedBrush,stroke:{radius:brushRadius,path:[[...p,pressureFor(e)]]}};drawOverlay();return;}if(state.brushes.length>=60)return notify('60 strokes reached. Export and reopen the image to continue painting.');drag={type:'stroke',target:'brushes',stroke:{kind:brushKind,value:brushValue,radius:brushRadius,feather:39,enabled:true,erasers:[],path:[[...p,pressureFor(e)]]}};}else if(tab==='retouch'){if(retouchMode==='magic'){beginMagicStroke(p);return;}if(clonePicking||!cloneAnchor){cloneAnchor=p;clonePicking=false;renderPanel();notify('Source selected. Paint over the distraction.');return;}if(state.clones.length>=60)return notify('60 clone strokes reached. Export and reopen the image to continue.');drag={type:'stroke',target:'clones',stroke:{radius:cloneRadius,opacity:cloneOpacity,dx:cloneAnchor[0]-p[0],dy:cloneAnchor[1]-p[1],enabled:true,path:[p]}};}drawOverlay();}
function movePointer(e){if(handleWorkspacePointerMove(e))return;if(!drag)return;const [nx,ny]=eventPoint(e),p=sourcePoint(nx,ny);if(drag.type==='magic'){moveMagicStroke(p);return;}if(['cropMove','cropHandle'].includes(drag.type)){cropPointerMove(nx,ny);return;}if(drag.type==='crop'){const [sx,sy]=drag.start,ex=snapped(nx),ey=snapped(ny);let w=Math.abs(ex-sx),h=Math.abs(ey-sy);if(cropRatio!=='free'){const ir=$('overlay').width/$('overlay').height,ratio=cropRatio==='original'?ir:Number(cropRatio);h=w*ir/ratio;const maxH=ey>=sy?1-sy:sy;if(h>maxH){h=maxH;w=h*ratio/ir;}}cropDraft={x:ex>=sx?sx:sx-w,y:ey>=sy?sy:sy-h,w:Math.max(.01,w),h:Math.max(.01,h)};cropDraft.x=cap(cropDraft.x,0,.99);cropDraft.y=cap(cropDraft.y,0,.99);cropDraft.w=Math.min(cropDraft.w,1-cropDraft.x);cropDraft.h=Math.min(cropDraft.h,1-cropDraft.y);for(const k of ['x','y','w','h'])if($('crop-'+k))$('crop-'+k).value=+(cropDraft[k]*100).toFixed(2);}else if(drag.type==='point'){const q=state.points[drag.index];q.x=p[0];q.y=p[1];document.querySelectorAll('[data-range="point.x"],[data-number="point.x"]').forEach(el=>el.value=q.x*100);document.querySelectorAll('[data-range="point.y"],[data-number="point.y"]').forEach(el=>el.value=q.y*100);}else if(drag.type==='stroke'||drag.type==='erase'){const path=drag.stroke.path,prev=path.at(-1),dist=Math.hypot(p[0]-prev[0],(p[1]-prev[1])*source.height/source.width),steps=Math.ceil(dist/(drag.stroke.radius/100*.3));if(path.length+steps>1200)return;for(let i=1;i<=steps;i++)path.push([prev[0]+(p[0]-prev[0])*i/steps,prev[1]+(p[1]-prev[1])*i/steps,(prev[2]??1)+(pressureFor(e)-(prev[2]??1))*i/steps]);}drawOverlay();}
function endPointer(e){if(handleWorkspacePointerEnd(e))return;if(!drag)return;if(drag.type==='magic'){endMagicStroke();return;}const d=drag;drag=null;if(d.type==='stroke'){state[d.target].push(d.stroke);if(d.target==='brushes')selectedBrush=state.brushes.length-1;else selectedClone=state.clones.length-1;changed(d.target==='clones'?'Clone stroke':'Brush stroke');renderPanel();}else if(d.type==='erase'){const st=state.brushes[d.index];st.erasers=st.erasers||[];st.erasers.push(d.stroke);changed('Erase selected mask');renderPanel();}else if(d.type==='point'){changed('Moved control point');renderPanel();}drawOverlay();}
function resetTool(){if(!source)return;const d=defaults();if(tab==='looks'){for(const k of ['adjust','effects','curves','hsl'])state[k]=d[k];state.curveInterpolation='linear';state.look='Original';}if(tab==='adjust'){state.adjust=d.adjust;state.curves=d.curves;state.hsl=d.hsl;state.curveInterpolation='linear';}if(tab==='crop'){state.geometry=d.geometry;cropDraft=copy(d.geometry.crop);cropRatio='free';}if(tab==='local'){state.points=[];state.brushes=[];}if(tab==='retouch'){if(retouchMode==='magic')state.eraser=eraserDefaults();else{state.clones=[];cloneAnchor=null;}}if(tab==='finish'){for(const k of ['effects','text','frame','blend'])state[k]=d[k];}changed('Reset '+tab);renderPanel();}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function cleanName(n){return n.replace(/\.(jpe?g|png|webp|json)$/i,'').replace(/[^a-zA-Z0-9_\- .]/g,'').trim().slice(0,90)||'photobench-edit';}
function downloadProject(){if(!source)return;commit('Edit');download(new Blob([JSON.stringify(project())],{type:'application/json'}),cleanName(source.name)+'.photobench.json');notify('Project downloaded with its source photo and editable settings.');}
function validURL(url){return typeof url==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=\r\n]+$/.test(url)&&url.length<=180000000;}
function normalizeSettingsV1(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Project settings are missing.');const d=defaults();
 const limits={adjust:{exposure:[-3,3],brightness:[-100,100],contrast:[-100,100],highlights:[-100,100],shadows:[-100,100],whites:[-100,100],blacks:[-100,100],saturation:[-100,100],vibrance:[-100,100],warmth:[-100,100],tint:[-100,100],sharpen:[0,100],structure:[0,100]},effects:{vignette:[-70,100],grain:[0,100],glow:[0,100],blur:[0,100],focusX:[0,1],focusY:[0,1],focusRadius:[2,80]},text:{x:[0,100],y:[0,100],size:[1,20]},frame:{size:[0,15]},blend:{opacity:[0,100]}};
 const number=(v,min,max,fallback)=>typeof v==='number'&&Number.isFinite(v)?cap(v,min,max):fallback;
 for(const [group,entries] of Object.entries(limits))for(const [k,[lo,hi]]of Object.entries(entries))d[group][k]=number(raw[group]?.[k],lo,hi,d[group][k]);
 for(const channel of ['rgb','r','g','b'])if(Array.isArray(raw.curves?.[channel])&&raw.curves[channel].length===5)d.curves[channel]=raw.curves[channel].map((v,i)=>number(v,0,100,i*25));
 const g=raw.geometry||{};d.geometry.quarter=Math.round(number(g.quarter,0,3,0));d.geometry.angle=number(g.angle,-30,30,0);d.geometry.flipX=g.flipX===true;d.geometry.flipY=g.flipY===true;const cr=g.crop||{};d.geometry.crop={x:number(cr.x,0,.99,0),y:number(cr.y,0,.99,0),w:number(cr.w,.01,1,1),h:number(cr.h,.01,1,1)};d.geometry.crop.w=Math.min(d.geometry.crop.w,1-d.geometry.crop.x);d.geometry.crop.h=Math.min(d.geometry.crop.h,1-d.geometry.crop.y);
 d.text.value=typeof raw.text?.value==='string'?raw.text.value.slice(0,300):'';d.text.shadow=raw.text?.shadow!==false;d.text.font=['sans-serif','serif','monospace'].includes(raw.text?.font)?raw.text.font:'sans-serif';for(const k of ['text','frame'])if(/^#[\da-f]{6}$/i.test(raw[k]?.color))d[k].color=raw[k].color;
 d.blend.mode=['screen','multiply','overlay','soft-light','source-over'].includes(raw.blend?.mode)?raw.blend.mode:'screen';d.blend.asset=typeof raw.blend?.asset==='string'?raw.blend.asset.slice(0,80):'';
 d.points=(Array.isArray(raw.points)?raw.points:[]).slice(0,12).filter(p=>p&&typeof p==='object').map(p=>({x:number(p.x,0,1,.5),y:number(p.y,0,1,.5),radius:number(p.radius,1,75,18),feather:number(p.feather,5,100,60),exposure:number(p.exposure,-3,3,0),saturation:number(p.saturation,-100,100,0),warmth:number(p.warmth,-100,100,0)}));
 for(const key of ['brushes','clones'])d[key]=(Array.isArray(raw[key])?raw[key]:[]).slice(0,60).filter(x=>x&&Array.isArray(x.path)).map(st=>{const path=st.path.slice(0,1200).filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)).map(p=>[cap(p[0],0,1),cap(p[1],0,1)]);return key==='brushes'?{path,radius:number(st.radius,.5,20,5),kind:['exposure','saturation','warmth'].includes(st.kind)?st.kind:'exposure',value:number(st.value,st.kind==='exposure'?-2:-100,st.kind==='exposure'?2:100,.5)}:{path,radius:number(st.radius,.5,15,3),opacity:number(st.opacity,5,100,85),dx:number(st.dx,-1,1,0),dy:number(st.dy,-1,1,0)};});
 d.look=typeof raw.look==='string'?raw.look.slice(0,50):'Custom';return d;}
async function validateProjectV1(data){if(data?.format!=='PHOTOBENCH'||![1,2,3,4].includes(data.schema))throw new Error('This is not a supported PHOTOBENCH schema 1–4 project.');if(!validURL(data.source?.dataURL))throw new Error('The project source image is missing or invalid.');const im=await imageFromURL(data.source.dataURL);if(im.naturalWidth>6000||im.naturalHeight>6000||im.naturalWidth*im.naturalHeight>20100000)throw new Error('Project source exceeds the 20-megapixel / 6000-pixel working limit.');const s=normalizeSettings(data.settings),as={};if(s.blend.asset){if(!/^asset-[0-9]+$/.test(s.blend.asset))throw new Error('Invalid second-image identifier.');const url=data.assets?.[s.blend.asset];if(!validURL(url))throw new Error('The second image is missing or invalid.');const bi=await imageFromURL(url);if(bi.naturalWidth>6000||bi.naturalHeight>6000||bi.naturalWidth*bi.naturalHeight>20100000)throw new Error('Second image exceeds the working limit.');Object.defineProperty(as,s.blend.asset,{value:url,enumerable:true,writable:true});}return{im,s,as,src:{name:typeof data.source.name==='string'?data.source.name.slice(0,150):'Imported photo',dataURL:data.source.dataURL,width:im.naturalWidth,height:im.naturalHeight,importWidth:Number(data.source.importWidth)||im.naturalWidth,importHeight:Number(data.source.importHeight)||im.naturalHeight,reduced:data.source.reduced===true}};}
async function importProject(file){if(!file)return;if(file.size>180*1024*1024)return notify('Project files must be smaller than 180 MB.');if(source&&!confirm('Replace the current session with this project?'))return;busy(true,'Opening project…');try{const data=JSON.parse(await file.text()),v=await validateProject(data);installPhoto(v.src,v.im,v.s,v.as,v.snapshots);notify('Project restored. All adjustments are editable.');}catch(e){fail(new Error('Project was not opened. '+e.message));}finally{busy(false);}}
function openExport(){if(!source)return;if(magicPending)return notify("Keep the Magic Eraser result or return to its mask before exporting.");commit('Edit');$('exportName').value=cleanName(source.name)+'-edit';$('exportDimensions').textContent=exportDimensions().join(' × ')+' pixels';$('exportDialog').showModal();}
async function makeExport(){const s=copy(state),result=await renderImage(s,Math.max(source.width,source.height),sourceImage,false),[w,h]=exportDimensions(),out=canvas(w,h),ctx=context(out);if($('exportFormat').value==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);}ctx.drawImage(result.canvas,0,0,w,h);return out;}
async function exportImage(print=false){if(!source||exportBusy)return;$('exportDialog').close();busy(true,print?'Preparing print…':'Rendering full-size image…');await new Promise(r=>setTimeout(r,30));try{const c=await makeExport();if(print){document.querySelectorAll('.print-only').forEach(e=>e.remove());const im=new Image();im.className='print-only';im.alt='Edited photograph';im.src=c.toDataURL('image/png');await im.decode();document.body.append(im);busy(false);window.print();}else{const type=$('exportFormat').value,q=Number($('exportQuality').value)/100,blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('The browser could not encode this export. Try a smaller size.')),type,q));if(blob.type!==type)throw new Error('This browser cannot export that format. Choose PNG or JPEG.');download(blob,cleanName($('exportName').value)+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[type]));notify(`Exported ${c.width} × ${c.height} pixels.`);}}catch(e){fail(e);}finally{busy(false);}}
function saveLook(){if(!source)return;const name=prompt('Name this reusable look (tone, curves, and effects):',state.look==='Custom'?'My look':state.look);if(!name?.trim())return;if(userLooks.length>=24)return notify('24 saved looks reached. Clear saved looks to start again.');const visible=effectiveSettings(state);userLooks.push({name:name.trim().slice(0,40),values:{adjust:copy(visible.adjust),curves:copy(visible.curves),curveInterpolation:visible.curveInterpolation,hsl:copy(visible.hsl),effects:copy(visible.effects)}});safePrefs('looks',JSON.stringify(userLooks));$('projectDialog').close();setTab('looks');notify('Look saved in this browser.');}
async function freshStart(){if(source&&!confirm('Clear this photo and its autosaved session? Download a project first to keep your work.'))return;clearMagicPreview();busy(true,'Clearing this session…');clearTimeout(dirtyTimer);clearTimeout(saveTimer);renderSerial++;source=null;sourceImage=null;state=defaults();snapshots=[];compareSnapshot='';assets={};assetImages={};history=[];historyIndex=-1;lastCommitted='';previewResult=null;beforeResult=null;cropDraft=null;revision++;try{await persist();}catch{}busy(false);$('projectDialog').close();syncButtons();renderPanel();drawHistogram();$('dimensions').textContent='Open a photo to begin';$('renderState').textContent='All processing stays on this device';}
function toggleCompare(on){if(!source)return;showBefore=on??!showBefore;$('compare').setAttribute('aria-pressed',String(showBefore));displayPhoto();}
function wireApp(){for(const id of ['openPhoto','emptyOpen'])$(id).onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{if(e.target.files[0])await replacePhoto(e.target.files[0]);e.target.value='';};$('jsonInput').onchange=async e=>{await importProject(e.target.files[0]);e.target.value='';};$('blendInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;busy(true,'Opening second photo…');try{const r=await decodeFile(file),id=newAssetId();const snapshotIds=new Set(snapshots.map(s=>s.settings.blend.asset).filter(Boolean));const total=portableAssetBytes(r.source.dataURL.length);if(total>150*1024*1024)throw new Error('The project would exceed its portable size limit. Remove snapshots that use other second images, or choose a smaller second photo.');assets[id]=r.source.dataURL;assetImages[id]=r.im;state.blend.asset=id;changed('Double exposure');renderPanel();}catch(e){fail(e);}finally{busy(false);}};
 $('sample').onclick=loadSample;$('undo').onclick=undo;$('redo').onclick=redo;$('compare').onclick=()=>toggleCompare();$('mode').onchange=setMode;$('theme').onchange=setTheme;$('zoom').onchange=sizePhoto;$('panelToggle').onclick=()=>{const hide=$('app').classList.toggle('panel-hidden');$('panelToggle').setAttribute('aria-expanded',String(!hide));sizePhoto();};new ResizeObserver(sizePhoto).observe($('workspace'));
 document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>setTab(el.dataset.tab));$('resetTool').onclick=resetTool;$('projectMenu').onclick=()=>$('projectDialog').showModal();$('helpOpen').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('saveProject').onclick=downloadProject;$('loadProject').onclick=()=>{$('projectDialog').close();$('jsonInput').click();};$('saveLook').onclick=saveLook;$('resetAll').onclick=()=>{state=defaults();changed('Reset all edits');cropDraft=tab==='crop'?copy(state.geometry.crop):null;$('projectDialog').close();renderPanel();};$('freshStart').onclick=freshStart;$('exportOpen').onclick=openExport;$('exportSize').onchange=()=>$('exportDimensions').textContent=exportDimensions().join(' × ')+' pixels';$('exportQuality').oninput=e=>$('qualityReadout').value=e.target.value+'%';$('exportFormat').onchange=e=>$('exportQuality').disabled=e.target.value==='image/png';$('doExport').onclick=()=>exportImage();$('printPhoto').onclick=()=>exportImage(true);
 $('overlay').addEventListener('pointerdown',beginPointer);$('overlay').addEventListener('pointermove',movePointer);$('overlay').addEventListener('pointerup',endPointer);$('overlay').addEventListener('pointercancel',endPointer);
 let dragDepth=0;document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});document.addEventListener('dragenter',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();dragDepth++;$('dropHint').hidden=false;}});document.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('dropHint').hidden=true;});document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('dropHint').hidden=true;if(exportBusy)return;const file=e.dataTransfer.files[0];if(!file)return;/\.json$/i.test(file.name)?importProject(file):replacePhoto(file);});
 document.addEventListener('keydown',e=>{if(exportBusy||document.querySelector('dialog[open]'))return;const typing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();downloadProject();return;}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.code==='Space'&&e.target.id==='workspace'){e.preventDefault();toggleCompare(true);}});document.addEventListener('keyup',e=>{if(e.code==='Space'&&e.target.id==='workspace')toggleCompare(false);});window.addEventListener('blur',()=>{if(showBefore)toggleCompare(false);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&source){commit('Edit');persist();}});window.addEventListener('beforeunload',e=>{if(magicPending||magicRunning||['unsaved','saving'].includes($('saveState').dataset.state)||(source&&$('saveState').dataset.state==='error')){e.preventDefault();e.returnValue='';}});
}
async function start(){document.body.dataset.mode=safePrefs('mode')||'easy';$('mode').value=document.body.dataset.mode;$('theme').value=safePrefs('theme')||'dark';document.documentElement.dataset.theme=$('theme').value;try{const arr=JSON.parse(safePrefs('looks')||'[]');userLooks=Array.isArray(arr)?arr.slice(0,24).filter(x=>x&&typeof x.name==='string'&&x.values).map(x=>{const s=normalizeSettings(x.values);return{name:x.name.slice(0,40),values:{adjust:s.adjust,curves:s.curves,curveInterpolation:s.curveInterpolation,hsl:s.hsl,effects:s.effects}};}):[];}catch{userLooks=[];}wireApp();$('cancelMagic').onclick=()=>magicCancel?.();setupWorkspace();setupV12();try{createWorker();}catch(e){fail(new Error('The browser could not start the image renderer. Use a current browser with JavaScript and workers enabled.'));}renderPanel();await openDB();try{const p=await dbRead();if(p){const v=await validateProject(p);installPhoto(v.src,v.im,v.s,v.as,v.snapshots);notify('Your last photo session has been restored.');}else if(dbFailed)setSave('error','! Autosave unavailable — save JSON');}catch(e){setSave('error','! Recovery failed');notify('The saved session could not be restored. Open a downloaded project JSON.');}if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol)){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>{$('offlineState').textContent='Offline reload is ready for this route.';}).catch(()=>{$('offlineState').textContent='For offline reload, serve sw.js beside this file over HTTPS or localhost.';});}else $('offlineState').textContent='Standalone mode: this HTML contains everything it needs to work offline.';}
// start() is called by the generated bundle after all modules are loaded.
