/* Magic Eraser: paint -> preview -> keep. All analysis stays in a local worker. */
let retouchMode='magic',magicAction='paint',magicShowMask=true,magicPending=null,magicWorker=null,magicCancel=null,magicRunning=false;
function clearMagicPreview(){if(magicPending){delete assets[magicPending.patch.asset];delete assetImages[magicPending.patch.asset];magicPending=null;}}
function magicPreviewSettings(s){if(magicPending&&JSON.stringify(state)===magicPending.base){s.eraser.removals.push(copy(magicPending.patch));s.enabled.eraser=true;}return s;}
function usedAssetIds(settings){const ids=settings.blend.asset?[settings.blend.asset]:[];for(const r of settings.eraser?.removals||[])ids.push(r.asset);return ids;}
function portableAssetBytes(extra=0){const ids=new Set([state,...snapshots.map(s=>s.settings)].flatMap(usedAssetIds));return(source?.dataURL.length||0)+extra+[...ids].reduce((sum,id)=>sum+(assets[id]?.length||0),0);}
function newAssetId(){let stamp=Date.now();while(assets['asset-'+stamp])stamp++;return'asset-'+stamp;}
async function validateRemovalAssets(v,data){const decoded=new Map();for(const settings of [v.s,...v.snapshots.map(s=>s.settings)])for(const r of settings.eraser.removals){
 if(r.x+r.w>v.src.width||r.y+r.h>v.src.height)throw new Error('A removal patch extends outside the source photo.');
 if(!decoded.has(r.asset)){const url=data.assets?.[r.asset];if(!validURL(url)||!url.startsWith('data:image/png;'))throw new Error('A Magic Eraser patch is missing or invalid.');const im=await imageFromURL(url);if(im.naturalWidth>6000||im.naturalHeight>6000||im.naturalWidth*im.naturalHeight>20100000)throw new Error('A removal patch exceeds the working limit.');decoded.set(r.asset,[im.naturalWidth,im.naturalHeight]);v.as[r.asset]=url;}
 const [w,h]=decoded.get(r.asset);if(w!==r.w||h!==r.h)throw new Error('A removal patch has inconsistent dimensions.');
}}
async function drawRemovalLayers(c,s,scaleX=1,scaleY=1,offsetX=0,offsetY=0){
 if(s.enabled?.eraser===false)return;const ctx=context(c);for(const r of s.eraser?.removals||[]){if(!assets[r.asset])throw new Error('A saved removal patch is missing. Reopen the project backup.');const im=assetImages[r.asset]||(assetImages[r.asset]=await imageFromURL(assets[r.asset])),x=(r.x-offsetX)*scaleX,y=(r.y-offsetY)*scaleY,w=r.w*scaleX,h=r.h*scaleY;
  ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.clearRect(x,y,w,h);ctx.drawImage(im,x,y,w,h);ctx.restore();
 }
}
function paintMagicMask(c,strokes,rect={x:0,y:0,w:source.width,h:source.height}){
 const ctx=context(c);ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.scale(c.width/rect.w,c.height/rect.h);ctx.translate(-rect.x,-rect.y);ctx.lineCap=ctx.lineJoin='round';ctx.fillStyle=ctx.strokeStyle='#fff';
 for(const st of strokes){ctx.globalCompositeOperation=st.mode==='subtract'?'destination-out':'source-over';const radius=st.radius/100*Math.min(source.width,source.height);ctx.lineWidth=radius*2;ctx.beginPath();st.path.forEach(([x,y],i)=>i?ctx.lineTo(x*source.width,y*source.height):ctx.moveTo(x*source.width,y*source.height));ctx.stroke();for(const point of [st.path[0],st.path.at(-1)])if(point){ctx.beginPath();ctx.arc(point[0]*source.width,point[1]*source.height,radius,0,Math.PI*2);ctx.fill();}}
 ctx.restore();ctx.globalCompositeOperation='source-over';
}
function magicBounds(strokes){let x0=source.width,y0=source.height,x1=0,y1=0;for(const st of strokes){if(st.mode==='subtract')continue;const radius=st.radius/100*Math.min(source.width,source.height);for(const [x,y]of st.path){x0=Math.min(x0,x*source.width-radius-2);x1=Math.max(x1,x*source.width+radius+2);y0=Math.min(y0,y*source.height-radius-2);y1=Math.max(y1,y*source.height+radius+2);}}x0=Math.max(0,Math.floor(x0));y0=Math.max(0,Math.floor(y0));x1=Math.min(source.width,Math.ceil(x1));y1=Math.min(source.height,Math.ceil(y1));return{x:x0,y:y0,w:x1-x0,h:y1-y0};}
function drawMagicOverlay(){if(tab!=='retouch'||retouchMode!=='magic'||!source||!previewResult||showBefore||magicPending||!magicShowMask)return;const w=Math.min(720,source.width),c=canvas(w,w*source.height/source.width),strokes=[...state.eraser.mask];if(drag?.type==='magic')strokes.push(drag.stroke);if(!strokes.length)return;paintMagicMask(c,strokes);const ctx=context(c);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#ff4b89aa';ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='source-over';const s=effectiveSettings(state);s.geometry.fill='transparent';s.geometry.expand.fill='transparent';const transformed=geometry(c,s,false,true).canvas;context($('overlay')).drawImage(transformed,0,0,$('overlay').width,$('overlay').height);}
function magicPanel(){const e=state.eraser;return`<section class="magic-panel"><h3>Magic Eraser</h3><p class="hint">Paint the entire object and a little space around its edges. Erase object builds a fill from unpainted surroundings.</p>${magicPending?`<div class="magic-preview" role="status"><strong>Preview ready · not kept yet</strong><p>Inspect the photo, then keep the result or try another fill.</p><button id="keepMagic" class="accent full">Keep result</button><div class="button-row"><button id="retryMagic">Try another fill</button><button id="refineMagicMask">Back to mask</button></div></div>`:`<div class="button-row"><button id="magicPaint" aria-pressed="${magicAction==='paint'}">Paint object</button><button id="magicSubtract" aria-pressed="${magicAction==='subtract'}">Subtract mask</button></div>${range('Eraser radius % of short side','eraser.radius',e.radius,.2,20,.1)}<label class="inline-toggle"><input id="magicShowMask" type="checkbox" ${magicShowMask?'checked':''}>Show removal mask</label><div class="button-row"><button id="undoMagicMask" ${e.mask.length?'':'disabled'}>Undo mask stroke</button><button id="clearMagicMask" ${e.mask.length?'':'disabled'}>Clear mask</button></div><button id="runMagic" class="accent large full" ${!e.mask.length?'disabled':''}>Erase object</button><p class="hint">${e.mask.length} / 60 mask strokes · ${e.removals.length} / 32 kept removals</p><details class="group filter-tuning"><summary>Fine-tune removal</summary>${range('Surroundings %','eraser.surroundings',e.surroundings,30,180,5)}${range('Texture patch radius','eraser.patch',e.patch,2,9,1)}<p class="hint">More surroundings searches farther from the object. Larger patches preserve broader texture patterns.</p></details>`}<div class="group"><button id="refineLastMagic" class="full" ${!e.removals.length||magicPending?'disabled':''}>Refine last kept removal</button><button id="removeLastMagic" class="text-button" ${!e.removals.length||magicPending?'disabled':''}>Remove last kept removal</button></div><p class="note">Works best on repeating textures and simple backgrounds. Hidden faces, text, and complex structures may need manual retouching. Processing stays on your device.</p></section>`;}
function retouchChooser(){return`<div class="button-row retouch-chooser"><button id="magicMode" aria-pressed="${retouchMode==='magic'}">Magic Eraser</button><button id="cloneMode" aria-pressed="${retouchMode==='clone'}">Clone brush</button></div>`;}
function wireMagicPanel(){if(tab!=='retouch')return;const bind=(id,fn)=>{if($(id))$(id).onclick=fn;};
 bind('magicMode',()=>{retouchMode='magic';renderPanel();});bind('cloneMode',()=>{clearMagicPreview();retouchMode='clone';renderPanel();requestRender();});
 bind('magicPaint',()=>{magicAction='paint';renderPanel();});bind('magicSubtract',()=>{magicAction='subtract';renderPanel();});
 if($('magicShowMask'))$('magicShowMask').onchange=e=>{magicShowMask=e.target.checked;drawOverlay();};
 bind('undoMagicMask',()=>{state.eraser.mask.pop();changed('Undo removal mask stroke');renderPanel();});bind('clearMagicMask',()=>{state.eraser.mask=[];changed('Clear removal mask');renderPanel();});
 bind('runMagic',()=>runMagic());bind('retryMagic',()=>runMagic(true));bind('refineMagicMask',()=>{clearMagicPreview();requestRender();renderPanel();});
 bind('keepMagic',()=>{if(!magicPending)return;if(magicPending.base!==JSON.stringify(state)){clearMagicPreview();notify('The photo changed. Run Erase object again.');renderPanel();return;}const patch=magicPending.patch;magicPending=null;state.eraser.removals.push(patch);state.eraser.mask=[];state.enabled.eraser=true;changed('Magic Eraser: kept removal');renderPanel();notify('Removal kept. Undo restores the object.');});
 bind('removeLastMagic',()=>{state.eraser.removals.pop();changed('Removed last repair');renderPanel();});
 bind('refineLastMagic',()=>{const last=state.eraser.removals.pop();state.eraser.mask=copy(last.mask);state.enabled.eraser=true;magicShowMask=true;changed('Refine last removal');renderPanel();});
}
function beginMagicStroke(p){if(magicPending){notify('Keep the result or choose Back to mask before painting.');return;}if(state.eraser.mask.length>=60){notify('60 mask strokes reached. Clear the mask or erase this object first.');return;}if(state.enabled.eraser===false){state.enabled.eraser=true;changed('Enable Magic Eraser');}magicShowMask=true;drag={type:'magic',stroke:{radius:state.eraser.radius,mode:magicAction,path:[p]}};drawOverlay();}
function moveMagicStroke(p){const path=drag.stroke.path,prev=path.at(-1);if(path.length>=1200)return;const distance=Math.hypot((p[0]-prev[0])*source.width,(p[1]-prev[1])*source.height);if(distance>=Math.max(.4,drag.stroke.radius/100*Math.min(source.width,source.height)*.12))path.push(p);drawOverlay();}
function endMagicStroke(){const st=drag.stroke;drag=null;state.eraser.mask.push(st);changed(st.mode==='subtract'?'Subtract removal mask':'Paint removal mask');renderPanel();}
async function runMagic(retry=false){
 if(!source||magicRunning||exportBusy)return;if(state.eraser.removals.length>=32)return notify('32 kept removals reached. Export a photo and reopen it to continue.');
 if(state.enabled.eraser===false){state.enabled.eraser=true;changed('Enable Magic Eraser');}
 if(retry){state.eraser.seed=state.eraser.seed%999999+1;changed('Try another removal fill');}clearMagicPreview();commit('Removal mask');magicRunning=true;busy(true,'Finding surrounding texture…');$('cancelMagic').hidden=false;document.querySelectorAll('header,main,footer').forEach(el=>el.inert=true);$('cancelMagic').focus();
 let cancelled=false,rejectWork;magicCancel=()=>{cancelled=true;magicWorker?.terminate();magicWorker=null;if(rejectWork)rejectWork(new Error('Removal cancelled. Your mask is still available.'));};
 try{
  await new Promise(r=>setTimeout(r,30));if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');
  const bounds=magicBounds(state.eraser.mask);if(bounds.w<=0||bounds.h<=0)throw new Error('Paint over an object first.');
  const margin=Math.max(32,Math.max(bounds.w,bounds.h)*state.eraser.surroundings/100),x=Math.max(0,Math.floor(bounds.x-margin)),y=Math.max(0,Math.floor(bounds.y-margin)),rect={x,y,w:Math.min(source.width,Math.ceil(bounds.x+bounds.w+margin))-x,h:Math.min(source.height,Math.ceil(bounds.y+bounds.h+margin))-y};
  const native=canvas(rect.w,rect.h);context(native).drawImage(sourceImage,-rect.x,-rect.y);await drawRemovalLayers(native,state,1,1,rect.x,rect.y);
  if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');
  const scale=Math.min(1,720/Math.max(rect.w,rect.h)),work=canvas(rect.w*scale,rect.h*scale),maskCanvas=canvas(work.width,work.height);context(work).drawImage(native,0,0,work.width,work.height);paintMagicMask(maskCanvas,state.eraser.mask,rect);
  const pixels=context(work).getImageData(0,0,work.width,work.height).data,maskRGBA=context(maskCanvas).getImageData(0,0,work.width,work.height).data,mask=new Uint8Array(work.width*work.height);for(let i=0;i<mask.length;i++)mask[i]=maskRGBA[i*4+3]>0?1:0;
  const url=URL.createObjectURL(new Blob([$('inpaintSource').textContent+`\nself.onmessage=e=>{try{const d=e.data,r=inpaintObject(new Uint8ClampedArray(d.pixels),new Uint8Array(d.mask),d.w,d.h,d.options,percent=>self.postMessage({progress:percent}));self.postMessage({dx:r.dx.buffer,dy:r.dy.buffer,shift:r.shift.buffer},[r.dx.buffer,r.dy.buffer,r.shift.buffer]);}catch(error){self.postMessage({error:error.message});}};`],{type:'text/javascript'}));
  magicWorker=new Worker(url);URL.revokeObjectURL(url);
  const result=await new Promise((resolve,reject)=>{rejectWork=reject;magicWorker.onmessage=e=>{if(e.data.progress!==undefined){$('busyText').textContent='Rebuilding the background… '+e.data.progress+'%';return;}e.data.error?reject(new Error(e.data.error)):resolve(e.data);};magicWorker.onerror=()=>reject(new Error('Removal could not finish. Try a smaller selection.'));magicWorker.postMessage({pixels:pixels.buffer,mask:mask.buffer,w:work.width,h:work.height,options:{patch:state.eraser.patch,seed:state.eraser.seed}},[pixels.buffer,mask.buffer]);});
  magicWorker.terminate();magicWorker=null;rejectWork=null;if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');
  $('busyText').textContent='Preparing native-resolution preview…';await new Promise(r=>setTimeout(r,20));if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');
  const offsetsX=new Int16Array(result.dx),offsetsY=new Int16Array(result.dy),correction=new Float32Array(result.shift),nativeData=context(native).getImageData(0,0,rect.w,rect.h).data;
  const patch=canvas(bounds.w,bounds.h),patchCtx=context(patch),blendMask=canvas(bounds.w,bounds.h);paintMagicMask(blendMask,state.eraser.mask,bounds);const coverage=context(blendMask).getImageData(0,0,bounds.w,bounds.h).data,output=patchCtx.createImageData(bounds.w,bounds.h),sx=rect.w/work.width,sy=rect.h/work.height;
  for(let py=0;py<bounds.h;py++){for(let px=0;px<bounds.w;px++){const nx=px+bounds.x-rect.x,ny=py+bounds.y-rect.y,i=(py*bounds.w+px)*4,original=(ny*rect.w+nx)*4,wx=cap(Math.floor((nx+.5)/sx),0,work.width-1),wy=cap(Math.floor((ny+.5)/sy),0,work.height-1),m=wy*work.width+wx,weight=coverage[i+3]/255;
    const xx=cap(Math.round(nx+offsetsX[m]*sx),0,rect.w-1),yy=cap(Math.round(ny+offsetsY[m]*sy),0,rect.h-1),donor=(yy*rect.w+xx)*4;
    for(let c=0;c<3;c++)output.data[i+c]=nativeData[original+c]+(nativeData[donor+c]+correction[m*3+c]-nativeData[original+c])*weight;output.data[i+3]=nativeData[original+3];
   }if(py%96===0){await new Promise(r=>setTimeout(r,0));if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');}}
  patchCtx.putImageData(output,0,0);const dataURL=patch.toDataURL('image/png');if(portableAssetBytes(dataURL.length)>150*1024*1024)throw new Error('This removal would exceed the project size limit. Export a photo and reopen it to continue.');
  const id=newAssetId(),im=await imageFromURL(dataURL);if(cancelled)throw new Error('Removal cancelled. Your mask is still available.');assets[id]=dataURL;assetImages[id]=im;magicPending={base:JSON.stringify(state),patch:{asset:id,...bounds,mask:copy(state.eraser.mask)}};
  requestRender();renderPanel();notify('Preview ready. Keep result saves the removal.');
 }catch(error){notify(error.message);renderPanel();}finally{magicWorker?.terminate();magicWorker=null;magicCancel=null;magicRunning=false;$('cancelMagic').hidden=true;busy(false);document.querySelectorAll('header,main,footer').forEach(el=>el.inert=false);if(tab==='retouch'&&retouchMode==='magic')$(magicPending?'keepMagic':'runMagic')?.focus();}
}
