/* v1.2 color refinement, recipes, edit inspector, and project snapshots. */
let snapshots=[],compareSnapshot='',hslBand='red',snapshotCache=new Map();
function geometry(c,s,uncropped=false,maskOnly=false){return geometryV12(c,s,uncropped,maskOnly);}
function previewLimit(){return previewQuality==='detail'&&source?Math.max(source.width,source.height):1280;}
function drawOverlay(){drawBaseOverlay();drawMaskOverlay();}
function outlinePoint(ctx,p){ctx.beginPath();let connected=false;for(let i=0;i<=96;i++){const angle=i/96*Math.PI*2,x=p.x+Math.cos(angle)*p.radius/100,y=p.y+Math.sin(angle)*p.radius/100*source.width/source.height;if(x<0||x>1||y<0||y>1){connected=false;continue;}const pt=displayMatrix.transformPoint({x:x*source.width*displayScale,y:y*source.height*displayScale});connected?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y);connected=true;}}
function drawClones(c,s){if(!s.clones.length)return;const ctx=context(c),original=canvas(c.width,c.height);context(original).drawImage(c,0,0);for(const st of s.clones){if(st.enabled===false)continue;for(const p of st.path){const r=Math.max(1,st.radius/100*c.width*(p[2]??1)),x=p[0]*c.width,y=p[1]*c.height,sx=x+st.dx*c.width,sy=y+st.dy*c.height,patch=canvas(r*2,r*2),pc=context(patch);pc.drawImage(original,sx-r,sy-r,2*r,2*r,0,0,2*r,2*r);pc.globalCompositeOperation='destination-in';const grad=pc.createRadialGradient(r,r,r*.35,r,r,r);grad.addColorStop(0,`rgba(0,0,0,${st.opacity/100})`);grad.addColorStop(1,'transparent');pc.fillStyle=grad;pc.fillRect(0,0,patch.width,patch.height);ctx.drawImage(patch,x-r,y-r);}}}
function curvePanelHTML(){return `<summary>Curves</summary><div class="two-cols"><label class="field">Channel<select id="curveChannel">${[['rgb','Master RGB'],['r','Red'],['g','Green'],['b','Blue']].map(([k,l])=>`<option value="${k}" ${k===curveChannel?'selected':''}>${l}</option>`).join('')}</select></label><label class="field">Interpolation<select id="curveInterpolation"><option value="linear" ${state.curveInterpolation==='linear'?'selected':''}>Linear</option><option value="smooth" ${state.curveInterpolation==='smooth'?'selected':''}>Smooth</option></select></label></div><svg id="curveGraph" class="curve-svg" viewBox="0 0 256 160" role="img" aria-label="Tone curve. Drag the nine output points or use the numeric controls below."><path d="M0 40H256M0 80H256M0 120H256M64 0V160M128 0V160M192 0V160" stroke="var(--line)" stroke-width=".5"/><path d="M0 160L256 0" stroke="var(--muted)" stroke-dasharray="3 3"/><path id="curveLine" fill="none" stroke="var(--accent)" stroke-width="2"/><g id="curveHandles"></g></svg><p class="hint">Drag a point vertically. Numeric controls provide exact output values.</p>${Array.from({length:9},(_,i)=>range(`Input ${i*12.5}% → output %`,`curves.${curveChannel}.${i}`,state.curves[curveChannel][i],0,100,.5)).join('')}<button id="linearCurve" class="full">Reset this curve</button>`;}
function updateCurveGraph(){if(!$('curveLine')||!$('curveGraph'))return;const points=state.curves[curveChannel],path=Array.from({length:129},(_,i)=>`${i?'L':'M'}${i*2},${160-curveValue(points,i/128,state.curveInterpolation)*1.6}`).join(' ');$('curveLine').setAttribute('d',path);$('curveHandles').innerHTML=points.map((v,i)=>`<circle data-curve-point="${i}" cx="${i*32}" cy="${160-v*1.6}" r="4" fill="var(--accent)" stroke="var(--bg)"/>`).join('');}
function hslPanelHTML(){const band=state.hsl[hslBand];return group('Color mixer',`<label class="field">Color range<select id="hslBand">${colorBands.map(([k,n])=>`<option value="${k}" ${k===hslBand?'selected':''}>${n}</option>`).join('')}</select></label>`+range('Hue shift (°)',`hsl.${hslBand}.hue`,band.hue,-60,60)+range('Saturation',`hsl.${hslBand}.saturation`,band.saturation,-100,100)+range('Lightness',`hsl.${hslBand}.lightness`,band.lightness,-100,100)+`<button id="resetBand" class="full">Reset this color range</button><p class="hint">Overlapping color ranges blend softly. Neutral grays are protected.</p>`,'advanced');}
function extendPanelV12(){const field=$('panelBody').querySelector('fieldset');if(!field)return;if(tab==='adjust'){const curves=$('curveChannel')?.closest('details');if(curves)curves.innerHTML=curvePanelHTML();field.insertAdjacentHTML('beforeend',hslPanelHTML());updateCurveGraph();}if(tab==='crop')field.insertAdjacentHTML('beforeend',geometryPanelExtras());
 const bypassed=editGroups.filter(k=>state.enabled[k]===false);if(bypassed.length)field.insertAdjacentHTML('afterbegin',`<p class="note">Bypassed in Edits: ${bypassed.map(k=>escapeHTML(groupNames[k])).join(', ')}. <button id="enableAll" class="text-button">Enable all</button></p>`);
 if(tab==='looks')field.insertAdjacentHTML('beforeend','<div class="group"><button id="recipePanelOpen" class="full" '+(!source?'disabled':'')+'>Export / apply recipe</button></div>');
}
function wirePanelV12(){const bind=(id,event,fn)=>{if($(id))$(id).addEventListener(event,fn);};
 bind('curveInterpolation','change',e=>{state.curveInterpolation=e.target.value;changed('Curve interpolation');updateCurveGraph();});bind('hslBand','change',e=>{hslBand=e.target.value;renderPanel();});bind('resetBand','click',()=>{state.hsl[hslBand]={hue:0,saturation:0,lightness:0};changed('Reset color range');renderPanel();});
 for(const [id,path]of[['perspectiveFill',['fill']],['perspectiveColor',['fillColor']],['expandFill',['expand','fill']],['expandColor',['expand','color']]])bind(id,'change',e=>{let target=state.geometry;for(const k of path.slice(0,-1))target=target[k];target[path.at(-1)]=e.target.value;changed('Canvas fill');});
 bind('enableAll','click',()=>{for(const k of editGroups)state.enabled[k]=true;changed('Enable all edits');renderPanel();});bind('recipePanelOpen','click',openRecipe);
 if($('curveGraph')){let point=-1;const graph=$('curveGraph'),move=e=>{if(point<0)return;const r=graph.getBoundingClientRect(),v=Math.round(cap(100-(e.clientY-r.top)/r.height*100,0,100)*2)/2;state.curves[curveChannel][point]=v;document.querySelectorAll(`[data-range="curves.${curveChannel}.${point}"],[data-number="curves.${curveChannel}.${point}"]`).forEach(el=>el.value=v);changed('Curve point',false);updateCurveGraph();};graph.onpointerdown=e=>{const r=graph.getBoundingClientRect();point=cap(Math.round((e.clientX-r.left)/r.width*8),0,8);graph.setPointerCapture(e.pointerId);move(e);};graph.onpointermove=move;graph.onpointerup=()=>{if(point>=0){point=-1;commit('Curve point');}};graph.onpointercancel=()=>{point=-1;commit('Curve point');};}
}
function normalizeSettings(raw){const d=normalizeSettingsV1(raw),num=(v,min,max,fallback)=>typeof v==='number'&&Number.isFinite(v)?cap(v,min,max):fallback;
 for(const k of ['rgb','r','g','b']){const v=raw.curves?.[k];if(Array.isArray(v)&&[5,9].includes(v.length))d.curves[k]=curveNine(v.map((x,i)=>num(x,0,100,i/(v.length-1)*100)));}d.curveInterpolation=raw.curveInterpolation==='smooth'?'smooth':'linear';
 for(const [k]of colorBands)for(const key of ['hue','saturation','lightness'])d.hsl[k][key]=num(raw.hsl?.[k]?.[key],key==='hue'?-60:-100,key==='hue'?60:100,0);
 for(const k of editGroups)d.enabled[k]=raw.enabled?.[k]!==false;
 const g=raw.geometry||{};d.geometry.perspectiveH=num(g.perspectiveH,-70,70,0);d.geometry.perspectiveV=num(g.perspectiveV,-70,70,0);d.geometry.fill=['transparent','color','edge'].includes(g.fill)?g.fill:'transparent';if(/^#[\da-f]{6}$/i.test(g.fillColor))d.geometry.fillColor=g.fillColor;
 for(const k of ['left','right','top','bottom'])d.geometry.expand[k]=num(g.expand?.[k],0,50,0);d.geometry.expand.fill=['transparent','color','edge','mirror'].includes(g.expand?.fill)?g.expand.fill:'transparent';if(/^#[\da-f]{6}$/i.test(g.expand?.color))d.geometry.expand.color=g.expand.color;
 const cleanPath=path=>(Array.isArray(path)?path:[]).slice(0,1200).filter(p=>Array.isArray(p)&&[2,3].includes(p.length)&&p.every(Number.isFinite)).map(p=>p.length===2?[cap(p[0],0,1),cap(p[1],0,1)]:[cap(p[0],0,1),cap(p[1],0,1),cap(p[2],.1,1)]);
 for(const type of ['brushes','clones'])d[type]=(Array.isArray(raw[type])?raw[type]:[]).slice(0,60).filter(x=>x&&Array.isArray(x.path)).map(st=>{const base={path:cleanPath(st.path),enabled:st.enabled!==false,radius:num(st.radius,.5,type==='brushes'?20:15,type==='brushes'?5:3)};if(type==='clones')return{...base,opacity:num(st.opacity,5,100,85),dx:num(st.dx,-1,1,0),dy:num(st.dy,-1,1,0)};const kind=['exposure','saturation','warmth'].includes(st.kind)?st.kind:'exposure';return{...base,kind,value:num(st.value,kind==='exposure'?-2:-100,kind==='exposure'?2:100,.5),feather:num(st.feather,0,100,39),erasers:(Array.isArray(st.erasers)?st.erasers:[]).slice(0,30).filter(e=>e&&Array.isArray(e.path)).map(e=>({radius:num(e.radius,.5,20,5),path:cleanPath(e.path)}))};});
 normalizeCreative(raw.effects,d.effects);return d;
}
function project(){const used={},all=[state,...snapshots.map(s=>s.settings)];for(const s of all)if(s.blend.asset&&assets[s.blend.asset])used[s.blend.asset]=assets[s.blend.asset];return{format:'PHOTOBENCH',schema:3,version:VERSION,savedAt:new Date().toISOString(),source:copy(source),settings:copy(state),snapshots:copy(snapshots),assets:copy(used)};}
async function validateProject(data){const v=await validateProjectV1(data);v.snapshots=(Array.isArray(data.snapshots)?data.snapshots:[]).slice(0,8).filter(s=>s&&typeof s.name==='string'&&s.settings).map((s,i)=>({id:'snap-import-'+i,name:s.name.slice(0,60),createdAt:typeof s.createdAt==='string'?s.createdAt.slice(0,40):'',settings:normalizeSettings(s.settings)}));
 for(const snap of v.snapshots){const id=snap.settings.blend.asset;if(!id||v.as[id])continue;if(!/^asset-[0-9]+$/.test(id)||!validURL(data.assets?.[id]))throw new Error('A snapshot contains an invalid second image.');const im=await imageFromURL(data.assets[id]);if(im.naturalWidth>6000||im.naturalHeight>6000||im.naturalWidth*im.naturalHeight>20100000)throw new Error('A snapshot second image exceeds the working limit.');v.as[id]=data.assets[id];}return v;
}
function exportDimensions(){if(!source)return[0,0];const [w,h]=fullDimensions(),limit=Number($('exportSize').value),sc=Math.min(1,8192/w,8192/h,Math.sqrt(32000000/(w*h)),limit?limit/Math.max(w,h):1);return[Math.max(1,Math.round(w*sc)),Math.max(1,Math.round(h*sc))];}
const groupNames={adjust:'Tone & color',curves:'Curves',hsl:'Color mixer',geometry:'Crop & geometry',points:'Control points',brushes:'Adjustment strokes',clones:'Clone strokes',effects:'Effects',text:'Text',frame:'Frame',blend:'Double exposure'};
function openStack(){if(!source)return;commit('Edit');$('projectDialog').close();renderStack();$('stackDialog').showModal();}
function renderStack(){const target=$('stackContent');target.innerHTML=`<p class="hint">Edits run in a fixed order. Bypass a group to compare its contribution; its settings are retained.</p><div class="edit-stack">${editGroups.map(k=>`<label class="stack-row"><input type="checkbox" data-group="${k}" ${state.enabled[k]?'checked':''}><span>${groupNames[k]}</span><small>${Array.isArray(state[k])?state[k].length+' items':state.enabled[k]?'Enabled':'Bypassed'}</small></label>`).join('')}</div><details class="group"><summary>Session undo history (${history.length})</summary><div class="history-list">${history.map((h,i)=>`<button data-history="${i}" aria-pressed="${i===historyIndex}">${i+1}. ${escapeHTML(h.label)}</button>`).join('')}</div></details><section class="group"><h3>Named snapshots</h3><p class="hint">Keep up to eight complete edit states with this project. Compare one, or restore it and continue editing.</p><div class="snapshot-add"><label class="sr-only" for="snapshotName">Snapshot name</label><input id="snapshotName" maxlength="60" placeholder="e.g. Warm print"><button id="captureSnapshot" class="accent" ${snapshots.length>=8?'disabled':''}>Capture</button></div><label class="field">Before / after comparison<select id="compareSource"><option value="">Original tones · current geometry</option>${snapshots.map(s=>`<option value="${s.id}" ${s.id===compareSnapshot?'selected':''}>${escapeHTML(s.name)}</option>`).join('')}</select></label>${snapshots.map(s=>`<div class="snapshot-row"><strong>${escapeHTML(s.name)}</strong><div class="button-row"><button data-compare-snap="${s.id}">Compare</button><button data-restore-snap="${s.id}">Restore</button><button data-delete-snap="${s.id}">Delete</button></div></div>`).join('')}</section>`;
 target.querySelectorAll('[data-group]').forEach(el=>el.onchange=()=>{state.enabled[el.dataset.group]=el.checked;changed('Bypass: '+groupNames[el.dataset.group]);el.closest('label').querySelector('small').textContent=el.checked?'Enabled':'Bypassed';renderPanel();});target.querySelectorAll('[data-history]').forEach(el=>el.onclick=()=>{historyIndex=Number(el.dataset.history);restoreHistory();renderStack();});
 $('captureSnapshot').onclick=()=>{const name=$('snapshotName').value.trim()||`Snapshot ${snapshots.length+1}`;snapshots.push({id:'snap-'+Date.now()+'-'+snapshots.length,name,createdAt:new Date().toISOString(),settings:copy(state)});markDirty();renderStack();notify('Snapshot captured. It will be saved with your project.');};
 $('compareSource').onchange=e=>{compareSnapshot=e.target.value;requestRender();};
 target.querySelectorAll('[data-compare-snap]').forEach(el=>el.onclick=async()=>{compareSnapshot=el.dataset.compareSnap;$('stackDialog').close();busy(true,'Preparing snapshot comparison…');try{beforeResult=await snapshotPreview(compareSnapshot);toggleCompare(true);}catch(e){fail(e);}finally{busy(false);}});
 target.querySelectorAll('[data-restore-snap]').forEach(el=>el.onclick=()=>{const snap=snapshots.find(s=>s.id===el.dataset.restoreSnap);state=copy(snap.settings);compareSnapshot='';cropDraft=tab==='crop'?copy(state.geometry.crop):null;changed('Restored snapshot: '+snap.name,true,true);renderPanel();renderStack();notify('Snapshot restored. Undo returns to your previous edits.');});
 target.querySelectorAll('[data-delete-snap]').forEach(el=>el.onclick=()=>{if(!confirm('Delete this named snapshot? Current edits will remain.'))return;snapshots=snapshots.filter(s=>s.id!==el.dataset.deleteSnap);if(compareSnapshot===el.dataset.deleteSnap){compareSnapshot='';showBefore=false;requestRender();}snapshotCache.clear();markDirty();renderStack();});
}
async function snapshotPreview(id){const snap=snapshots.find(s=>s.id===id);if(!snap)return originalPreview(state,tab==='crop');const key=id+':'+previewQuality;if(snapshotCache.has(key))return snapshotCache.get(key);const result=await renderImage(snap.settings,previewLimit(),sourceImage,false);snapshotCache.clear();snapshotCache.set(key,result.canvas);return result.canvas;}
function recipeData(){const s=effectiveSettings(state),settings={};for(const k of ['adjust','curves','curveInterpolation','hsl','effects'])settings[k]=copy(s[k]);if($('recipeGeometry').checked)settings.geometry=copy(s.geometry);if($('recipeFinish').checked){settings.text=copy(s.text);settings.frame=copy(s.frame);}return{format:'PHOTOBENCH_RECIPE',schema:2,version:VERSION,name:$('recipeName').value.trim().slice(0,60)||'My photo recipe',settings};}
function openRecipe(){if(!source)return;$('projectDialog').close();$('recipeName').value=state.look==='Custom'?'My photo recipe':state.look;$('recipeDialog').showModal();}
async function applyRecipeFile(file){if(!file)return;if(file.size>1024*1024)return notify('A recipe must be smaller than 1 MB.');try{const data=JSON.parse(await file.text());if(data.format!=='PHOTOBENCH_RECIPE'||![1,2].includes(data.schema)||!data.settings||typeof data.settings!=='object')throw new Error('Choose a PHOTOBENCH recipe JSON.');const s=normalizeSettings(data.settings),keys=['adjust','curves','hsl','effects'];if(data.settings.geometry)keys.push('geometry');if(data.settings.text)keys.push('text');if(data.settings.frame)keys.push('frame');const message='Apply “'+(typeof data.name==='string'?data.name.slice(0,60):'Recipe')+'”? This replaces '+keys.map(k=>groupNames[k]).join(', ')+'.';if(!confirm(message))return;for(const k of keys){state[k]=copy(s[k]);state.enabled[k]=true;}state.curveInterpolation=s.curveInterpolation;state.look=typeof data.name==='string'?data.name.slice(0,40):'Recipe';cropDraft=tab==='crop'?copy(state.geometry.crop):null;changed('Applied recipe',true,true);$('recipeDialog').close();renderPanel();notify('Recipe applied. Undo restores your previous settings.');}catch(e){fail(new Error('Recipe was not applied. '+e.message));}}
function setupV12(){
 document.body.insertAdjacentHTML('beforeend',`<dialog id="stackDialog" aria-labelledby="stackTitle"><div class="dialog-head"><h2 id="stackTitle">Edits &amp; snapshots.</h2><button id="stackClose" aria-label="Close edit inspector">×</button></div><div id="stackContent"></div></dialog><dialog id="recipeDialog" aria-labelledby="recipeTitle"><div class="dialog-head"><h2 id="recipeTitle">Take your look with you.</h2><button id="recipeClose" aria-label="Close recipes">×</button></div><p>A recipe carries tone, curves, the color mixer, and effects between photos. It contains no photograph.</p><label class="field">Recipe name<input id="recipeName" maxlength="60"></label><label class="inline-toggle"><input type="checkbox" id="recipeGeometry">Include crop, perspective, and canvas expansion</label><label class="inline-toggle"><input type="checkbox" id="recipeFinish">Include text and frame</label><p class="hint">Control points, painted masks, clones, second images, and snapshots stay with the project.</p><div class="dialog-buttons"><button id="recipeDownload" class="accent">Download recipe JSON</button><button id="recipeImport">Apply recipe JSON</button></div></dialog><input type="file" id="recipeInput" accept=".json,application/json" hidden>`);
 $('stackOpen').onclick=openStack;$('snapshotOpen').onclick=openStack;$('stackClose').onclick=()=>$('stackDialog').close();$('recipeOpen').onclick=openRecipe;$('recipeClose').onclick=()=>$('recipeDialog').close();$('recipeDownload').onclick=()=>{const data=recipeData();download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),cleanName(data.name)+'.photobench-recipe.json');notify('Recipe downloaded.');};$('recipeImport').onclick=()=>$('recipeInput').click();$('recipeInput').onchange=async e=>{await applyRecipeFile(e.target.files[0]);e.target.value='';};
 const last=safePrefs('tab');if(['looks','adjust','crop','local','retouch','finish'].includes(last)&&!($('mode').value==='easy'&&['local','retouch'].includes(last)))tab=last;
}
